MODULE wimcomm

  USE bpsd_kinds
  USE bpsd_constants
  IMPLICIT NONE

  INTEGER:: NZMAX,NWMAX,NTMAX,MODELW,MODELP,IDEBUG_wim(1)
  REAL(rkind):: ZMIN,ZMAX,PN0,DBDZ,ANX,BETA,TMAX,DZMAX,DZWID,PZCL
  COMPLEX(rkind):: CER1,CEL1,CER2,CEL2

  INTEGER:: NLEN,NWID,NTSET
  REAL(rkind):: TMAXST
  REAL(rkind),ALLOCATABLE,DIMENSION(:):: ZA,AKD1,AKD2,TT
  COMPLEX(rkind),ALLOCATABLE,DIMENSION(:):: CE,CV,CPWR,CFK1,CFK2
  COMPLEX(rkind),ALLOCATABLE,DIMENSION(:,:):: CK,CFKS1,CFKS2
  COMPLEX(rkind):: CA1,CB1,CD1,CE1,CF1,CG1
  COMPLEX(rkind):: CA2,CB2,CD2,CE2,CF2,CG2
  COMPLEX(rkind):: CPTOT
  REAL(rkind),DIMENSION(0:1,0:1):: D0,D1,D2
  REAL(rkind),DIMENSION(0:1,0:1,0:1):: D3
  INTEGER:: wave_dump,id_wave_dump,fid_wave_dump
  CHARACTER(LEN=256):: kid_wave_dump
  
CONTAINS

  SUBROUTINE wim_allocate

    INTEGER,SAVE:: NZMAX_save = 0
    INTEGER,SAVE:: NWMAX_save = 0
    INTEGER,SAVE:: NTMAX_save = 0

    IF(NZMAX == NZMAX_save .AND. &
       NWMAX == NWMAX_save .AND. &
       NTMAX == NTMAX_save) RETURN

    IF(NZMAX_save /= 0) CALL wim_deallocate

    NLEN=3*NZMAX+7   ! 3*(nzmax+1) + 4  (E on nodes and outgoing R and L)
    IF(NZMAX.EQ.NWMAX) THEN
       NWID=3*NZMAX+7
    ELSE
       NWID=6*NWMAX+5  ! 2 * 3 * (NWMAX+1) -1
    END IF

    ALLOCATE(ZA(0:NZMAX))
    ALLOCATE(CE(NLEN),CK(NWID,NLEN),CV(NLEN))
    ALLOCATE(CPWR(0:NZMAX))
    ALLOCATE(AKD1(0:NZMAX),AKD2(0:NZMAX))
    ALLOCATE(TT(NTMAX))
    ALLOCATE(CFK1(NTMAX),CFKS1(NTMAX,3))
    ALLOCATE(CFK2(NTMAX),CFKS2(NTMAX,3))

    NZMAX_save=NZMAX
    NWMAX_save=NWMAX
    NTMAX_save=NTMAX

    NTSET=0
    TMAXST=0.D0 

    RETURN
  END SUBROUTINE wim_allocate

  SUBROUTINE wim_deallocate

    DEALLOCATE(ZA)
    DEALLOCATE(CE,CK,CV)
    DEALLOCATE(CPWR)
    DEALLOCATE(AKD1,AKD2)
    DEALLOCATE(TT)
    DEALLOCATE(CFK1,CFKS1)
    DEALLOCATE(CFK2,CFKS2)

    RETURN
  END SUBROUTINE wim_deallocate
END MODULE wimcomm
