! ticomm.f90

MODULE ticomm_parm

  ! pt_pl=>PT: the merge added PT(NSM) to plcomm_parm, but ti owns a local
  ! PT(NSM) (computed from PTPR/PTPP in tiinit). Rename plcomm's PT away so
  ! ti's local PT stays authoritative (P0a = no behaviour change; folding ti
  ! onto plcomm's shared PT is P2 param-dedup, not this merge).
  USE plcomm,pm=>pa,pt_pl=>PT
  USE commpi

!     NSM=100 ! imported from plcomm

! IMPORTED FROM plcomm
!     RR,RA,RKAP,RDLT,BB,RIP,
!     NSM,NSMAX,
!     NPA(NSM),PM(NSM),PZ(NSM),PN(NSM),PNS(NSM),PTPR(NSM),PTPP(NSM),PTS(NSM),
!     PU(NSM),PUS(NSM),ID_NS(NSM),KID_NS(NSM)
!     PROFN1,PROFN2,PROFT1,PROFT2,PROFU1,PROFU2
!     MODELG,model_prof,MODELQ,MODEL_NPROF
!     KNAMEQ,KNAMEQ2,KNAMTR
!     MODEFR,MODEFW,IDEBUG
!     RHOA,Q0,QA (not an input parameter for tr)

  INTEGER:: NZMIN_NS(NSM),NZMAX_NS(NSM),NZINI_NS(NSM)
  INTEGER:: MODEL_BND(3,NSM)
  INTEGER:: NRMAX,NTMAX,NTSTEP,NGTSTEP,NGRSTEP
  INTEGER:: ngt_allocate_step,ngr_allocate_step
  INTEGER:: MAXLOOP,MATTYPE
  INTEGER:: MODEL_EQB,MODEL_EQN,MODEL_EQT,MODEL_EQU
  INTEGER:: MODEL_KAI,MODEL_DRR,MODEL_VR,MODEL_NC
  INTEGER:: MODEL_NF,MODEL_NB,MODEL_EC,MODEL_LH,MODEL_IC
  INTEGER:: MODEL_CD,MODEL_SYNC
  INTEGER:: MODEL_PEL,MODEL_PSC

  REAL(rkind):: PT(NSM)
  REAL(rkind):: PROFJ1,PROFJ2
  REAL(rkind):: DT
  REAL(rkind):: EPSLOOP
  REAL(rkind):: EPSMAT
  REAL(rkind):: glog_min

  REAL(rkind):: DN0,DT0,DU0,VDN0,VDT0,VDU0,DR0,DRS
  REAL(rkind):: DN0_NS(NSM),DT0_NS(NSM),DU0_NS(NSM)
  REAL(rkind):: VDN0_NS(NSM),VDT0_NS(NSM),VDU0_NS(NSM)
  REAL(rkind):: PNBIN,PNBR0,PNBRW,PNBENG,PNBRTG
  REAL(rkind):: PECIN,PECR0,PECRW,PECTOE,PECNPR
  REAL(rkind):: PLHIN,PLHR0,PLHRW,PLHTOE,PLHNPR
  REAL(rkind):: PICIN,PICR0,PICRW,PICTOE,PICNPR
  REAL(rkind):: PNBCD,PECCD,PLHCD,PICCD,PBSCD
  REAL(rkind):: PELIN,PELR0,PELRW,PELPAT(NSM)
  REAL(rkind):: PELTS,PELDT,PELTE,PELRAD,PELVEL
  REAL(rkind):: PSCIN,PSCR0,PSCRW,PSCPAT(NSM)
  REAL(rkind):: SYNC_WALL,SYNC_CONV
  REAL(rkind):: BND_VALUE(3,NSM)

  CHARACTER(LEN=80):: KNAMLOG
  CHARACTER(LEN=80):: adpost_dir,adpost_filename
  CHARACTER(LEN=80):: adas_adf11_dir,adas_adf11_filename

CONTAINS

  SUBROUTINE open_ticomm_parm
    RETURN
  END SUBROUTINE open_ticomm_parm

END MODULE ticomm_parm

MODULE ticomm
  
  USE ticomm_parm
  USE commpi
  IMPLICIT NONE

  REAL(rkind),PARAMETER:: RKEV = AEE*1.D3

  INTEGER:: NR_START,NR_END
  INTEGER:: istart,iend,imax,jwidth

  REAL(rkind):: T
  INTEGER,DIMENSION(:),ALLOCATABLE:: &  !nsa_max
       ID_NSA,NSA_UP,NSA_DN,NS_NSA
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &  !nsa_max
       PMA,PZA,PZ2A
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &  !nsa_max
       PRADE
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &  !nsa_max,NRMAX
       RNA,RTA,RUA
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &  !NRMAX
       RBP,RQP,RJP
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &  !nsa_max,NRMAX
       rnatot,rnuatot,rntatot,rnaave,ruaave,rtaave
  
  INTEGER:: ND_adpost(NSM)
  INTEGER:: NEQMAX,NGTMAX,NGRMAX

!     ****** CONTROL VARIABLES ******

  INTEGER:: NT
  INTEGER:: icount_loop,icount_mat
  INTEGER:: icount_loop_max,icount_mat_max
  REAL(rkind):: residual_loop,residual_loop_max

!     ****** GRID VARIBALES ******

  REAL(rkind):: DR
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: RM,RG

!     ****** BOUNDARY CONDITION VARIABLES ******

  INTEGER,DIMENSION(:,:),ALLOCATABLE:: MODEL_BNDA
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: BND_VALUEA

!     ****** MATRIX VARIBALES ******

  INTEGER:: nsa_max
  INTEGER, DIMENSION(:),ALLOCATABLE:: NSA_NEQ,NV_NEQ
  INTEGER, DIMENSION(:,:),ALLOCATABLE:: NEQ_NVNSA
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE :: MAT_LOCAL
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: VEC_LOCAL,VEC_GLOBAL
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: SOL_BASE,SOL_PREV,SOL_NEW
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: VAL_EDGE

!     ****** PROFILE VARIBALES ******

  REAL(rkind),DIMENSION(:),ALLOCATABLE :: ZEFF,BETA,BETAP

!     ****** COEF VARIABLSE *****

  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: DNTB,DTTB,DUTB
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: DNNC,DTNC,DUNC
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: VDNTB,VDTTB,VDUTB
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: VDNNC,VDTNC,VDUNC

!     ****** SOURCE VARIABLES ******

  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: & ! (nsa_max,NRMAX)
       PNB,SNB,AJNB,PEC,AJEC,PLH,AJLH,PIC,AJIC, &
       PNF,SNF,SPEL,SPSC,POH,PRB,PRC,PRL, &
       PCX,PIE,SCX,SIE,AJBS
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &! (NRMAX)
       AJR,AJOHR,EZOHR,QPR,AJCDR,AJBSR
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &! (NRMAX)
       PNBR,SNBR,AJNBR,PECR,AJECR,PLHR,AJLHR,PICR,AJICR, &
       PNFR,SNFR,SPELR,SPSCR,POHR,PRBR,PRCR,PRLR, &
       PCXR,PIER,SCXR,SIER
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &! (nsa_max)
       PNBS,SNBS,AJNBS,PECS,AJECS,PLHS,AJLHS,PICS,AJICS, &
       PNFS,SNFS,SPELS,SPSCS,POHS,PRBS,PRCS,PRLS, &
       PCXS,PIES,SCXS,SIES,AJBSS
  REAL(rkind):: &
       AJTOT,AJOHTOT,EZOHTOT,QPTOT,AJCDTOT,AJBSTOT
  REAL(rkind):: &
       PNBTOT,SNBTOT,AJNBTOT,PECTOT,AJECTOT,PLHTOT,AJLHTOT,PICTOT,AJICTOT, &
       PNFTOT,SNFTOT,SPELTOT,SPSCTOT,POHTOT,PRBTOT,PRCTOT,PRLTOT, &
       PCXTOT,PIETOT,SCXTOT,SIETOT

!     ****** MATRIX VARIABLES ******

  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: & ! (nsa_max,NRMAX)
       SSIN,VSIN,PSIN,AJIN
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: & ! (nsa_max,NRMAX)
       DDN,VVN,DDT,VVT,DDU,VVU
  REAL(rkind),DIMENSION(:,:,:),ALLOCATABLE:: & ! (nsa_max,nsa_max,NRMAX)
       CCN,CCT,CCU

!     ****** EQUILIBRIUM INTERFACE VARIABLES ******

  REAL(rkind):: voltot,DVRHOS
  REAL(rkind)                 :: BPSEQ,RIPEQ
  REAL(rkind), DIMENSION(:),ALLOCATABLE :: &  ! (NRM)
       RHOTR, PRHO, HJRHO, VTRHO, TRHO, TTRHO, DVRHO, RKPRHO, ABRHO, ABVRHO, &
       ARRHO, AR1RHO, AR2RHO,  RJCB, EPSRHO, BPRHO, RMJRHO, RMNRHO, &
       TTRHOG, DVRHOG, RKPRHOG, ABRHOG, ABVRHOG, ARRHOG, AR1RHOG, AR2RHOG, &
       ABB2RHOG, AIB2RHOG, ARHBRHOG, RMJRHOG, RMNRHOG, RDPVRHOG, &
       PSITRHO, PSIPRHO, PPPRHO, PIQRHO, PIRHO, FACTQ, &
       PVOLRHOG, PSURRHOG, ABB1RHO

!     ****** NCLASS ******
! TRNCL
  INTEGER:: NSCLMAX
  INTEGER,DIMENSION(:),ALLOCATABLE:: NSCL_NSA,NSA_NSCL
  REAL(rkind), DIMENSION(:)    ,ALLOCATABLE :: & !  (NRM)
       AJBSNC, ETANC, AJEXNC
  REAL(rkind), DIMENSION(:,:)  ,ALLOCATABLE :: & !  (NRM,NSM)
       CJBSP, CJBST, ADNCG, AVNCG
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: & !  (NRM,NSM,NSM)
       AKNCP, AKNCT, ADNCP, ADNCT, AKLP, AKLD, ADLP, ADLD
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: & !  (NRM,5,NSM)
       RGFLS,   RQFLS

CONTAINS

  SUBROUTINE allocate_ticomm(ierr)

    IMPLICIT NONE
    INTEGER,INTENT(OUT):: ierr
    INTEGER,SAVE:: nrmax_save=0
    INTEGER,SAVE:: nsa_max_save=0
    INTEGER:: id
    ierr = 0

    ! Skip re-allocation only when dims unchanged AND arrays still
    ! allocated. The pure dim check (the original two-line guard) is
    ! broken for finalize+reinit cycles inside libtiapi.so: after
    ! deallocate_ticomm has freed every array, ID_NSA et al. are
    ! UNALLOCATED but nrmax_save still holds the previous nrmax, so
    ! the unguarded check would early-return and the next access of
    ! ID_NSA / RNA / RTA segfaults (use-after-free). The ALLOCATED
    ! probe is the minimum-diff fix; binary tiX runs once per process
    ! so it never hits this path either way.
    IF(nrmax.EQ.nrmax_save .AND. &
       nsa_max.EQ.nsa_max_save .AND. &
       ALLOCATED(ID_NSA)) RETURN

    IF(ALLOCATED(ID_NSA)) CALL deallocate_ticomm

    ALLOCATE(ID_NSA(nsa_max),NS_NSA(nsa_max),STAT=IERR)
             id=1;IF(IERR.NE.0) GOTO 900
    ALLOCATE(NSA_UP(nsa_max),NSA_DN(nsa_max),STAT=IERR)
             id=2;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PMA(nsa_max),PZA(nsa_max),PZ2A(nsa_max),STAT=IERR)
             id=3;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRADE(nsa_max,NRMAX),STAT=IERR)
             id=4;IF(IERR.NE.0) GOTO 900
    ALLOCATE(RNA(nsa_max,NRMAX),RTA(nsa_max,NRMAX),RUA(nsa_max,NRMAX), &
                                         STAT=IERR)
             id=5;IF(IERR.NE.0) GOTO 900
    ALLOCATE(RBP(NRMAX),RQP(NRMAX),RJP(NRMAX),STAT=IERR)
             id=6;IF(IERR.NE.0) GOTO 900
    ! Initialize to zero so the regression dump (tiregress.f90) does
    ! not emit subnormal garbage when these arrays are unassigned
    ! (e.g. NSMAX=1 cases never write to them). Reproducible across
    ! runs is essential for Layer 1 equivalence comparison.
    RBP = 0.0_rkind; RQP = 0.0_rkind; RJP = 0.0_rkind
    ALLOCATE(rnatot(nsa_max),rnuatot(nsa_max),rntatot(nsa_max),STAT=IERR)
             id=7;IF(IERR.NE.0) GOTO 900
    ALLOCATE(rnaave(nsa_max),ruaave(nsa_max),rtaave(nsa_max))
             id=8;IF(IERR.NE.0) GOTO 900

    ALLOCATE(RM(NRMAX),RG(0:NRMAX),STAT=IERR)
             id=11;IF(IERR.NE.0) GOTO 900
    ALLOCATE(ZEFF(NRMAX),BETA(NRMAX),BETAP(NRMAX),STAT=IERR)
             id=12;IF(IERR.NE.0) GOTO 900
    ! Same zero-init rationale as RBP/RQP/RJP above.
    ZEFF = 0.0_rkind; BETA = 0.0_rkind; BETAP = 0.0_rkind
    ALLOCATE(DNTB(nsa_max,NRMAX),STAT=IERR)
             id=13;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DTTB(nsa_max,NRMAX),STAT=IERR)
             id=14;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DUTB(nsa_max,NRMAX),STAT=IERR)
             id=15;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DNNC(nsa_max,NRMAX),STAT=IERR)
             id=16;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DTNC(nsa_max,NRMAX),STAT=IERR)
             id=17;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DUNC(nsa_max,NRMAX),STAT=IERR)
             id=18;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VDNTB(nsa_max,NRMAX),STAT=IERR)
             id=19;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VDTTB(nsa_max,NRMAX),STAT=IERR)
             id=20;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VDUTB(nsa_max,NRMAX),STAT=IERR)
             id=21;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VDNNC(nsa_max,NRMAX),STAT=IERR)
             id=22;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VDTNC(nsa_max,NRMAX),STAT=IERR)
             id=23;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VDUNC(nsa_max,NRMAX),STAT=IERR)
             id=24;IF(IERR.NE.0) GOTO 900

!     ****** SOURCE VARIABLES ******

    ALLOCATE(PNB(nsa_max,NRMAX),STAT=IERR); id=25;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNB(nsa_max,NRMAX),STAT=IERR); id=26;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJNB(nsa_max,NRMAX),STAT=IERR); id=27;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PEC(nsa_max,NRMAX),STAT=IERR); id=28;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJEC(nsa_max,NRMAX),STAT=IERR); id=29;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PLH(nsa_max,NRMAX),STAT=IERR); id=30;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJLH(nsa_max,NRMAX),STAT=IERR); id=31;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIC(nsa_max,NRMAX),STAT=IERR); id=32;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJIC(nsa_max,NRMAX),STAT=IERR); id=33;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PNF(nsa_max,NRMAX),STAT=IERR); id=34;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNF(nsa_max,NRMAX),STAT=IERR); id=35;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPEL(nsa_max,NRMAX),STAT=IERR); id=36;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPSC(nsa_max,NRMAX),STAT=IERR); id=37;IF(IERR.NE.0) GOTO 900
    ALLOCATE(POH(nsa_max,NRMAX),STAT=IERR); id=38;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRB(nsa_max,NRMAX),STAT=IERR); id=39;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRC(nsa_max,NRMAX),STAT=IERR); id=40;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRL(nsa_max,NRMAX),STAT=IERR); id=41;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PCX(nsa_max,NRMAX),STAT=IERR); id=42;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIE(nsa_max,NRMAX),STAT=IERR); id=43;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SCX(nsa_max,NRMAX),STAT=IERR); id=44;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SIE(nsa_max,NRMAX),STAT=IERR); id=45;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJBS(nsa_max,NRMAX),STAT=IERR); id=46;IF(IERR.NE.0) GOTO 900

    ALLOCATE(AJR(NRMAX),STAT=IERR); id=51;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJOHR(NRMAX),STAT=IERR); id=52;IF(IERR.NE.0) GOTO 900
    ALLOCATE(EZOHR(NRMAX),STAT=IERR); id=53;IF(IERR.NE.0) GOTO 900
    ALLOCATE(QPR(NRMAX),STAT=IERR); id=54;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJCDR(NRMAX),STAT=IERR); id=55;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJBSR(NRMAX),STAT=IERR); id=56;IF(IERR.NE.0) GOTO 900

    ALLOCATE(PNBR(NRMAX),STAT=IERR); id=61;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNBR(NRMAX),STAT=IERR); id=62;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJNBR(NRMAX),STAT=IERR); id=63;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PECR(NRMAX),STAT=IERR); id=64;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJECR(NRMAX),STAT=IERR); id=65;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PLHR(NRMAX),STAT=IERR); id=66;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJLHR(NRMAX),STAT=IERR); id=67;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PICR(NRMAX),STAT=IERR); id=68;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJICR(NRMAX),STAT=IERR); id=69;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PNFR(NRMAX),STAT=IERR); id=70;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNFR(NRMAX),STAT=IERR); id=71;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPELR(NRMAX),STAT=IERR); id=72;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPSCR(NRMAX),STAT=IERR); id=73;IF(IERR.NE.0) GOTO 900
    ALLOCATE(POHR(NRMAX),STAT=IERR); id=74;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRBR(NRMAX),STAT=IERR); id=75;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRCR(NRMAX),STAT=IERR); id=76;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRLR(NRMAX),STAT=IERR); id=77;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PCXR(NRMAX),STAT=IERR); id=78;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIER(NRMAX),STAT=IERR); id=79;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SCXR(NRMAX),STAT=IERR); id=81;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SIER(NRMAX),STAT=IERR); id=82;IF(IERR.NE.0) GOTO 900

    ALLOCATE(PNBS(nsa_max),STAT=IERR); id=101;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNBS(nsa_max),STAT=IERR); id=102;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJNBS(nsa_max),STAT=IERR); id=103;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PECS(nsa_max),STAT=IERR); id=104;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJECS(nsa_max),STAT=IERR); id=105;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PLHS(nsa_max),STAT=IERR); id=106;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJLHS(nsa_max),STAT=IERR); id=107;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PICS(nsa_max),STAT=IERR); id=108;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJICS(nsa_max),STAT=IERR); id=109;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PNFS(nsa_max),STAT=IERR); id=110;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNFS(nsa_max),STAT=IERR); id=111;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPELS(nsa_max),STAT=IERR); id=112;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPSCS(nsa_max),STAT=IERR); id=113;IF(IERR.NE.0) GOTO 900
    ALLOCATE(POHS(nsa_max),STAT=IERR); id=114;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRBS(nsa_max),STAT=IERR); id=115;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRCS(nsa_max),STAT=IERR); id=116;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRLS(nsa_max),STAT=IERR); id=117;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PCXS(nsa_max),STAT=IERR); id=118;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIES(nsa_max),STAT=IERR); id=119;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SCXS(nsa_max),STAT=IERR); id=120;IF(IERR.NE.0) GOTO 900
    ALLOCATE(SIES(nsa_max),STAT=IERR); id=121;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJBSS(nsa_max),STAT=IERR); id=122;IF(IERR.NE.0) GOTO 900

    ALLOCATE(SSIN(nsa_max,NRMAX),STAT=IERR); id=201;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VSIN(nsa_max,NRMAX),STAT=IERR); id=202;IF(IERR.NE.0) GOTO 900
    ALLOCATE(PSIN(nsa_max,NRMAX),STAT=IERR); id=203;IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJIN(nsa_max,NRMAX),STAT=IERR); id=204;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DDN(nsa_max,NRMAX),STAT=IERR); id=205;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VVN(nsa_max,NRMAX),STAT=IERR); id=206;IF(IERR.NE.0) GOTO 900
    ALLOCATE(CCN(nsa_max,nsa_max,NRMAX),STAT=IERR)
                                            id=207;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DDT(nsa_max,NRMAX),STAT=IERR); id=208;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VVT(nsa_max,NRMAX),STAT=IERR); id=209;IF(IERR.NE.0) GOTO 900
    ALLOCATE(CCT(nsa_max,nsa_max,NRMAX),STAT=IERR)
                                            id=210;IF(IERR.NE.0) GOTO 900
    ALLOCATE(DDU(nsa_max,NRMAX),STAT=IERR); id=211;IF(IERR.NE.0) GOTO 900
    ALLOCATE(VVU(nsa_max,NRMAX),STAT=IERR); id=212;IF(IERR.NE.0) GOTO 900
    ALLOCATE(CCU(nsa_max,nsa_max,NRMAX),STAT=IERR)
                                            id=213;IF(IERR.NE.0) GOTO 900

    ALLOCATE(DVRHO(NRMAX),STAT=IERR); id=214;IF(IERR.NE.0) GOTO 900
    ALLOCATE(MODEL_BNDA(3,nsa_max),STAT=IERR); id=215;IF(IERR.NE.0) GOTO 900
    ALLOCATE(BND_VALUEA(3,nsa_max),STAT=IERR); id=216;IF(IERR.NE.0) GOTO 900

    nrmax_save = nrmax
    nsa_max_save = nsa_max
    RETURN

 900 CONTINUE
    WRITE(6,*) "XX  TICOMM ALLOCATION ERROR IERR.id=",ierr,id
    CALL deallocate_ticomm
    RETURN

  END SUBROUTINE allocate_ticomm


  SUBROUTINE deallocate_ticomm
    IMPLICIT NONE

    IF(ALLOCATED(ID_NSA   ))     DEALLOCATE(ID_NSA   )
    IF(ALLOCATED(NS_NSA   ))     DEALLOCATE(NS_NSA   )
    IF(ALLOCATED(NSA_UP   ))     DEALLOCATE(NSA_UP   )
    IF(ALLOCATED(NSA_DN   ))     DEALLOCATE(NSA_DN   )
    IF(ALLOCATED(PMA      ))     DEALLOCATE(PMA      )
    IF(ALLOCATED(PZA      ))     DEALLOCATE(PZA      )
    IF(ALLOCATED(PZ2A     ))     DEALLOCATE(PZ2A     )
    IF(ALLOCATED(PRADE    ))     DEALLOCATE(PRADE    )
    IF(ALLOCATED(RNA      ))     DEALLOCATE(RNA      )
    IF(ALLOCATED(RTA      ))     DEALLOCATE(RTA      )
    IF(ALLOCATED(RUA      ))     DEALLOCATE(RUA      )
    IF(ALLOCATED(RBP      ))     DEALLOCATE(RBP      )
    IF(ALLOCATED(RQP      ))     DEALLOCATE(RQP      )
    IF(ALLOCATED(RJP      ))     DEALLOCATE(RJP      )

    IF(ALLOCATED(rnatot   ))     DEALLOCATE(rnatot   )
    IF(ALLOCATED(rnuatot   ))     DEALLOCATE(rnuatot   )
    IF(ALLOCATED(rntatot   ))     DEALLOCATE(rntatot   )
    IF(ALLOCATED(rnaave   ))     DEALLOCATE(rnaave   )
    IF(ALLOCATED(ruaave   ))     DEALLOCATE(ruaave   )
    IF(ALLOCATED(rtaave   ))     DEALLOCATE(rtaave   )

    IF(ALLOCATED(RM       ))     DEALLOCATE(RM       )
    IF(ALLOCATED(RG       ))     DEALLOCATE(RG       )

    IF(ALLOCATED(ZEFF     ))     DEALLOCATE(ZEFF     )
    IF(ALLOCATED(BETA     ))     DEALLOCATE(BETA     )
    IF(ALLOCATED(BETAP    ))     DEALLOCATE(BETAP    )

    IF(ALLOCATED(DNTB     ))     DEALLOCATE(DNTB     )
    IF(ALLOCATED(DTTB     ))     DEALLOCATE(DTTB     )
    IF(ALLOCATED(DUTB     ))     DEALLOCATE(DUTB     )
    IF(ALLOCATED(DNNC     ))     DEALLOCATE(DNNC     )
    IF(ALLOCATED(DTNC     ))     DEALLOCATE(DTNC     )
    IF(ALLOCATED(DUNC     ))     DEALLOCATE(DUNC     )
    IF(ALLOCATED(VDNTB    ))     DEALLOCATE(VDNTB    )
    IF(ALLOCATED(VDTTB    ))     DEALLOCATE(VDTTB    )
    IF(ALLOCATED(VDUTB    ))     DEALLOCATE(VDUTB    )
    IF(ALLOCATED(VDNNC    ))     DEALLOCATE(VDNNC    )
    IF(ALLOCATED(VDTNC    ))     DEALLOCATE(VDTNC    )
    IF(ALLOCATED(VDUNC    ))     DEALLOCATE(VDUNC    )

    IF(ALLOCATED(PNB      ))     DEALLOCATE(PNB      )
    IF(ALLOCATED(SNB      ))     DEALLOCATE(SNB      )
    IF(ALLOCATED(AJNB     ))     DEALLOCATE(AJNB     )
    IF(ALLOCATED(PEC      ))     DEALLOCATE(PEC      )
    IF(ALLOCATED(AJEC     ))     DEALLOCATE(AJEC     )
    IF(ALLOCATED(PLH      ))     DEALLOCATE(PLH      )
    IF(ALLOCATED(AJLH     ))     DEALLOCATE(AJLH     )
    IF(ALLOCATED(PIC      ))     DEALLOCATE(PIC      )
    IF(ALLOCATED(AJIC     ))     DEALLOCATE(AJIC     )
    IF(ALLOCATED(PNF      ))     DEALLOCATE(PNF      )
    IF(ALLOCATED(SNF      ))     DEALLOCATE(SNF      )
    IF(ALLOCATED(SPEL     ))     DEALLOCATE(SPEL     )
    IF(ALLOCATED(SPSC     ))     DEALLOCATE(SPSC     )
    IF(ALLOCATED(POH      ))     DEALLOCATE(POH      )
    IF(ALLOCATED(PRB      ))     DEALLOCATE(PRB      )
    IF(ALLOCATED(PRC      ))     DEALLOCATE(PRC      )
    IF(ALLOCATED(PRL      ))     DEALLOCATE(PRL      )
    IF(ALLOCATED(PCX      ))     DEALLOCATE(PCX      )
    IF(ALLOCATED(PIE      ))     DEALLOCATE(PIE      )
    IF(ALLOCATED(SCX      ))     DEALLOCATE(SCX      )
    IF(ALLOCATED(SIE      ))     DEALLOCATE(SIE      )
    IF(ALLOCATED(AJBS     ))     DEALLOCATE(AJBS     )

    IF(ALLOCATED(AJR      ))     DEALLOCATE(AJR      )
    IF(ALLOCATED(AJOHR    ))     DEALLOCATE(AJOHR    )
    IF(ALLOCATED(EZOHR    ))     DEALLOCATE(EZOHR    )
    IF(ALLOCATED(QPR      ))     DEALLOCATE(QPR      )
    IF(ALLOCATED(AJCDR    ))     DEALLOCATE(AJCDR    )
    IF(ALLOCATED(AJBSR    ))     DEALLOCATE(AJBSR    )

    IF(ALLOCATED(PNBR     ))     DEALLOCATE(PNBR     )
    IF(ALLOCATED(SNBR     ))     DEALLOCATE(SNBR     )
    IF(ALLOCATED(AJNBR    ))     DEALLOCATE(AJNBR    )
    IF(ALLOCATED(PECR     ))     DEALLOCATE(PECR     )
    IF(ALLOCATED(AJECR    ))     DEALLOCATE(AJECR    )
    IF(ALLOCATED(PLHR     ))     DEALLOCATE(PLHR     )
    IF(ALLOCATED(AJLHR    ))     DEALLOCATE(AJLHR    )
    IF(ALLOCATED(PICR     ))     DEALLOCATE(PICR     )
    IF(ALLOCATED(AJICR    ))     DEALLOCATE(AJICR    )
    IF(ALLOCATED(PNFR     ))     DEALLOCATE(PNFR     )
    IF(ALLOCATED(SNFR     ))     DEALLOCATE(SNFR     )
    IF(ALLOCATED(SPELR    ))     DEALLOCATE(SPELR    )
    IF(ALLOCATED(SPSCR    ))     DEALLOCATE(SPSCR    )
    IF(ALLOCATED(POHR     ))     DEALLOCATE(POHR     )
    IF(ALLOCATED(PRBR     ))     DEALLOCATE(PRBR     )
    IF(ALLOCATED(PRCR     ))     DEALLOCATE(PRCR     )
    IF(ALLOCATED(PRLR     ))     DEALLOCATE(PRLR     )
    IF(ALLOCATED(PCXR     ))     DEALLOCATE(PCXR     )
    IF(ALLOCATED(PIER     ))     DEALLOCATE(PIER     )
    IF(ALLOCATED(SCXR     ))     DEALLOCATE(SCXR     )
    IF(ALLOCATED(SIER     ))     DEALLOCATE(SIER     )

    IF(ALLOCATED(PNBS     ))     DEALLOCATE(PNBS     )
    IF(ALLOCATED(SNBS     ))     DEALLOCATE(SNBS     )
    IF(ALLOCATED(AJNBS    ))     DEALLOCATE(AJNBS    )
    IF(ALLOCATED(PECS     ))     DEALLOCATE(PECS     )
    IF(ALLOCATED(AJECS    ))     DEALLOCATE(AJECS    )
    IF(ALLOCATED(PLHS     ))     DEALLOCATE(PLHS     )
    IF(ALLOCATED(AJLHS    ))     DEALLOCATE(AJLHS    )
    IF(ALLOCATED(PICS     ))     DEALLOCATE(PICS     )
    IF(ALLOCATED(AJICS    ))     DEALLOCATE(AJICS    )
    IF(ALLOCATED(PNFS     ))     DEALLOCATE(PNFS     )
    IF(ALLOCATED(SNFS     ))     DEALLOCATE(SNFS     )
    IF(ALLOCATED(SPELS    ))     DEALLOCATE(SPELS    )
    IF(ALLOCATED(SPSCS    ))     DEALLOCATE(SPSCS    )
    IF(ALLOCATED(POHS     ))     DEALLOCATE(POHS     )
    IF(ALLOCATED(PRBS     ))     DEALLOCATE(PRBS     )
    IF(ALLOCATED(PRCS     ))     DEALLOCATE(PRCS     )
    IF(ALLOCATED(PRLS     ))     DEALLOCATE(PRLS     )
    IF(ALLOCATED(PCXS     ))     DEALLOCATE(PCXS     )
    IF(ALLOCATED(PIES     ))     DEALLOCATE(PIES     )
    IF(ALLOCATED(SCXS     ))     DEALLOCATE(SCXS     )
    IF(ALLOCATED(SIES     ))     DEALLOCATE(SIES     )
    IF(ALLOCATED(AJBSS    ))     DEALLOCATE(AJBSS    )

    IF(ALLOCATED(SSIN     ))     DEALLOCATE(SSIN     )
    IF(ALLOCATED(VSIN     ))     DEALLOCATE(VSIN     )
    IF(ALLOCATED(PSIN     ))     DEALLOCATE(PSIN     )
    IF(ALLOCATED(AJIN     ))     DEALLOCATE(AJIN     )
    IF(ALLOCATED(DDN      ))     DEALLOCATE(DDN      )
    IF(ALLOCATED(VVN      ))     DEALLOCATE(VVN      )
    IF(ALLOCATED(CCN      ))     DEALLOCATE(CCN      )
    IF(ALLOCATED(DDT      ))     DEALLOCATE(DDT      )
    IF(ALLOCATED(VVT      ))     DEALLOCATE(VVT      )
    IF(ALLOCATED(CCT      ))     DEALLOCATE(CCT      )
    IF(ALLOCATED(DDU      ))     DEALLOCATE(DDU      )
    IF(ALLOCATED(VVU      ))     DEALLOCATE(VVU      )
    IF(ALLOCATED(CCU      ))     DEALLOCATE(CCU      )

    IF(ALLOCATED(DVRHO    ))     DEALLOCATE(DVRHO    )
    IF(ALLOCATED(MODEL_BNDA))    DEALLOCATE(MODEL_BNDA)
    IF(ALLOCATED(BND_VALUEA))    DEALLOCATE(BND_VALUEA)

    RETURN

  END SUBROUTINE deallocate_ticomm

  SUBROUTINE allocate_neqmax(ierr)

    IMPLICIT NONE
    INTEGER,INTENT(OUT):: ierr
    INTEGER,SAVE:: nrmax_save=0
    INTEGER,SAVE:: neqmax_save=0
    ierr = 0

    ! Same finalize+reinit guard as allocate_ticomm above: the pure
    ! dim check breaks when deallocate_neqmax has just freed the
    ! arrays but the SAVE counters still hold the previous values.
    IF(nrmax_save==nrmax .AND. &
       neqmax_save==neqmax .AND. &
       ALLOCATED(MAT_LOCAL)) RETURN

    IF(ALLOCATED(MAT_LOCAL)) CALL deallocate_neqmax

    ALLOCATE(NSA_NEQ(NEQMAX),NV_NEQ(NEQMAX),NEQ_NVNSA(3,0:nsa_max),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(MAT_LOCAL(NEQMAX,3*NEQMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(VEC_LOCAL(NEQMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(VEC_GLOBAL(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(SOL_BASE(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(SOL_PREV(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(SOL_NEW(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(VAL_EDGE(NEQMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900

    nrmax_save = nrmax
    neqmax_save = neqmax

    RETURN
             
 900 CONTINUE
    WRITE(6,*) "XX  TICOMM NEQMAX ALLOCATION ERROR IERR=",ierr
    CALL deallocate_neqmax
    RETURN
  END SUBROUTINE allocate_neqmax

  SUBROUTINE deallocate_neqmax

    IMPLICIT NONE

    DEALLOCATE(NSA_NEQ,NV_NEQ,NEQ_NVNSA)
    DEALLOCATE(MAT_LOCAL,VEC_LOCAL,VEC_GLOBAL,SOL_BASE,SOL_PREV,SOL_NEW)
    DEALLOCATE(VAL_EDGE)

    RETURN
  END SUBROUTINE deallocate_neqmax

END MODULE ticomm
