MODULE TRCOM1
  USE TRCOM0, ONLY : NRMAX, NRUM, NTUM, NEQMAXM
  USE bpsd_kinds,ONLY: rkind
  IMPLICIT NONE

! TMSLC
  INTEGER              :: NTAMAX, NTXMAX, NTXMAX1
  REAL(rkind)                 :: PNBI
  REAL(rkind), DIMENSION(NTUM):: TMU, TMU1

! TRERU
  REAL(rkind), DIMENSION(:,:),ALLOCATABLE :: RTEXU, RTIXU, RNEXU, RTEXEU, RTIXEU, RNEXEU   ! (NTUM,NRUM)

! TRINS
  INTEGER:: INS

! TRLCL
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: A, B, C                ! (NVM,NVM,NRM)
  REAL(rkind), DIMENSION(:,:)  ,ALLOCATABLE :: D                      ! (NVM,NRM)
  REAL(rkind), DIMENSION(:,:)  ,ALLOCATABLE :: RD, PPA, PPB, PPC      ! (NEQM,NRM)

! TRUFC
  INTEGER              :: NMCHK
  INTEGER,DIMENSION(2) :: NREMAX
  REAL,DIMENSION(:,:),ALLOCATABLE :: GRE   ! (NRUM,2)
  CHARACTER(LEN=80)       :: KDIRX


  CONTAINS

  SUBROUTINE ALLOCATE_TRCOM1(IERR)

    INTEGER, INTENT(OUT):: IERR
    IERR = 0
    IF(ALLOCATED(RTEXU)) CALL DEALLOCATE_TRCOM1
    ALLOCATE(RTEXU(NTUM,NRUM), RTIXU(NTUM,NRUM), RNEXU(NTUM,NRUM),STAT=IERR)
      IF(IERR.NE.0) GOTO 900
    ALLOCATE(RTEXEU(NTUM,NRUM), RTIXEU(NTUM,NRUM), RNEXEU(NTUM,NRUM),STAT=IERR)
      IF(IERR.NE.0) GOTO 900
    ALLOCATE(A(NEQMAXM,NEQMAXM,NRMAX), B(NEQMAXM,NEQMAXM,NRMAX),STAT=IERR)
      IF(IERR.NE.0) GOTO 900
    ALLOCATE(C(NEQMAXM,NEQMAXM,NRMAX), D(NEQMAXM,NRMAX),STAT=IERR)
      IF(IERR.NE.0) GOTO 900
    ALLOCATE(RD(NEQMAXM,NRMAX), PPA(NEQMAXM,NRMAX), PPB(NEQMAXM,NRMAX),STAT=IERR)
      IF(IERR.NE.0) GOTO 900
    ALLOCATE(PPC(NEQMAXM,NRMAX), GRE(NRUM,2),STAT=IERR)
      IF(IERR.NE.0) GOTO 900

    ! Defensive zero-init (see PR #121/#123 pattern): libtrapi.so
    ! finalize+reinit cycle can reuse heap chunks with stale values.
    ! A/B/C/D/RD/PPA/PPB/PPC are banded-system scratch arrays rebuilt
    ! each step by trexec, but the reinit-without-trprep path reads
    ! them before they are fully overwritten; the RTE/RTI/RNE* UFILE
    ! scratch arrays are only partially written when MDLUF<=0, so the
    ! unused slots would carry prior-run values. GRE is partially
    ! populated by trufile (NREMAX-dependent).
    RTEXU(:,:)  = 0.D0
    RTIXU(:,:)  = 0.D0
    RNEXU(:,:)  = 0.D0
    RTEXEU(:,:) = 0.D0
    RTIXEU(:,:) = 0.D0
    RNEXEU(:,:) = 0.D0
    A(:,:,:)    = 0.D0
    B(:,:,:)    = 0.D0
    C(:,:,:)    = 0.D0
    D(:,:)      = 0.D0
    RD(:,:)     = 0.D0
    PPA(:,:)    = 0.D0
    PPB(:,:)    = 0.D0
    PPC(:,:)    = 0.D0
    GRE(:,:)    = 0.0
    RETURN
 900 CONTINUE
    WRITE(6,*) "XX TRCOM1 ALLOCATION ERROR IERR=",IERR
    CALL DEALLOCATE_ERR_TRCOM1
    RETURN
  END SUBROUTINE ALLOCATE_TRCOM1

  SUBROUTINE DEALLOCATE_TRCOM1
    DEALLOCATE(RTEXU, RTIXU, RNEXU, RTEXEU, RTIXEU, RNEXEU)
    DEALLOCATE(A, B, C, D, RD, PPA, PPB, PPC, GRE)
    RETURN
  END SUBROUTINE DEALLOCATE_TRCOM1

  SUBROUTINE DEALLOCATE_ERR_TRCOM1
    IF(ALLOCATED(RTEXU ))     DEALLOCATE(RTEXU )
    IF(ALLOCATED(RTIXU ))     DEALLOCATE(RTIXU )
    IF(ALLOCATED(RNEXU ))     DEALLOCATE(RNEXU )
    IF(ALLOCATED(RTEXEU))     DEALLOCATE(RTEXEU)
    IF(ALLOCATED(RTIXEU))     DEALLOCATE(RTIXEU)
    IF(ALLOCATED(RNEXEU))     DEALLOCATE(RNEXEU)
    IF(ALLOCATED(A     ))     DEALLOCATE(A     )
    IF(ALLOCATED(B     ))     DEALLOCATE(B     )
    IF(ALLOCATED(C     ))     DEALLOCATE(C     )
    IF(ALLOCATED(D     ))     DEALLOCATE(D     )
    IF(ALLOCATED(RD    ))     DEALLOCATE(RD    )
    IF(ALLOCATED(PPA   ))     DEALLOCATE(PPA   )
    IF(ALLOCATED(PPB   ))     DEALLOCATE(PPB   )
    IF(ALLOCATED(PPC   ))     DEALLOCATE(PPC   )
    IF(ALLOCATED(GRE   ))     DEALLOCATE(GRE   )
    RETURN
  END SUBROUTINE DEALLOCATE_ERR_TRCOM1


END MODULE TRCOM1
