MODULE trcomm_profile
!     ****** PROFILE / SOURCE / COEFFICIENT / EQUILIBRIUM /
!            NCLASS / UFILE / GRAPHIC / ADDITIONAL VARIABLES ******
! TRVAR / TRPFL / TRSRC / TRCEF / TREQV1 / TRNCL / TRSVU / TRPROF /
! TRADD(arrays) / TRPLR
  USE TRCOM0, ONLY: rkind, NFM, NTM, NGM, NLM, NCTM, NCGM, NCRTM, NTUM
  IMPLICIT NONE
  PUBLIC

!     ****** FUNDAMENTAL VARIABLES ******
! TRVAR
  REAL(rkind), DIMENSION(:)  ,ALLOCATABLE :: & ! (NRM)
       RG, RM, RHOM, RHOG, BP, RDP, RPSI
  REAL(rkind), DIMENSION(:,:),ALLOCATABLE :: & ! (NRM,NSTM)
       RN, RT, RU
  REAL(rkind), DIMENSION(:,:),ALLOCATABLE :: & ! (NRM,NFM)
       RW

!     ****** PROFILE VARIABLES ******
! TRPFL
  REAL(rkind), DIMENSION(:,:), ALLOCATABLE :: & ! (NRM,NFM)
       RNF, RTF
  REAL(rkind), DIMENSION(:)  , ALLOCATABLE :: & ! (NRM)
       ANC, ANFE, ANNU, ZEFF, PZC, PZFE, BETA, BETAP, BETAL, BETAPL, &
       BETAQ, PBM, PADD, VTOR, VPAR, VPRP, VPOL, WROT, ER, VEXB, WEXB, AGMP, &
       VEXBP, WEXBP

!     ****** SOURCE VARIABLES ******
! TRSRC
  REAL(rkind), DIMENSION(10)      :: &
       RTG
  REAL(rkind), DIMENSION(:),     ALLOCATABLE :: & ! (NRM)
       AJ, AJOH, EZOH, QP, AJTOR, AJNB, AJRF, AJBS, QPINV, PNB, SNB, &
       PBIN, PNF, SNF, PFIN, POH, PRB, PRC, PRL, PRSUM, &
       PCX, PIE, SIE, SCX, TSIE, TSCX
  REAL(rkind), DIMENSION(:,:),   ALLOCATABLE :: & ! (NRM,NSTM)
       PIN, SSIN, PBCL, PFCL, PRF, SPE
  REAL(rkind), DIMENSION(:,:),   ALLOCATABLE :: & ! (NRM,NSM)
       RGFLX,SPSC
  REAL(rkind), DIMENSION(:,:),   ALLOCATABLE :: & ! (NRM,3)
       AJRFV
  REAL(rkind), DIMENSION(:,:,:), ALLOCATABLE :: & ! (NRM,NSTM,3)
       PRFV

!     ****** COEFFICIENT VARIABLES ******
! TRCEF
  REAL(rkind), DIMENSION(:)  ,ALLOCATABLE :: & ! (NRM)
       ETA, S, ALPHA, RKCV, TAUB, TAUF, TAUK
  REAL(rkind), DIMENSION(:,:),ALLOCATABLE :: & ! (NRM,NSTM)
       AK, AVK, AD, AV, AKNC, AKDW, ADNC, ADDW, AVNC, AVDW, AVKNC, AVKDW
  REAL(rkind), DIMENSION(:,:),ALLOCATABLE :: & ! (NRM,4)
       VGR1, VGR2, VGR3, VGR4
  CHARACTER(LEN=46)       :: &
       KGR1, KGR2, KGR3, KGR4

!     ****** GRAPHIC DATA VARIABLES ******
! TRPLR
  REAL, DIMENSION(NTM) :: GT, GTS
  REAL, DIMENSION(NGM) :: GTR
  REAL, DIMENSION(NLM) :: GBL
  REAL, DIMENSION(NTM,8) :: GYT
  REAL, DIMENSION(NTM,NCTM) :: GVT
  REAL, DIMENSION(NLM,10) :: GBR, GBRH, GBP1, GBAN
  REAL, DIMENSION(:)    ,ALLOCATABLE :: GRM                       ! (NRM)
  REAL, DIMENSION(:)    ,ALLOCATABLE :: GRG                       ! (NRMP)
  REAL, DIMENSION(:,:)  ,ALLOCATABLE :: GJB, GAD                  ! (NRMP,4)
  REAL, DIMENSION(:,:)  ,ALLOCATABLE :: GET                       ! (NRMP,5)
  REAL, DIMENSION(:,:)  ,ALLOCATABLE :: GAK                       ! (NRMP,6)
  REAL, DIMENSION(:,:)  ,ALLOCATABLE :: GYR, GER                  ! (NRMP,8)
  REAL, DIMENSION(:,:)  ,ALLOCATABLE :: GPNB                      ! (4*NRM,10)
  REAL, DIMENSION(:,:,:),ALLOCATABLE :: GVR                       ! (NRMP,NGM,NCGM)
  REAL, DIMENSION(:,:,:),ALLOCATABLE :: GVRT                       ! (NRM,NGM,NCRTM)
  INTEGER              :: NGR, NGT, NGST
  INTEGER,DIMENSION(10):: NLMAX
  CHARACTER(10),DIMENSION(NCTM):: KVT
  CHARACTER(10),DIMENSION(NCRTM):: KVRT

!     ****** EQUILIBRIUM INTERFACE VARIABLES ******
! TREQV1
  REAL(rkind)                 :: BPSEQ,RIPEQ
  REAL(rkind), DIMENSION(:),ALLOCATABLE :: &  ! (NRM)
       RHOTR, PRHO, HJRHO, VTRHO, TRHO, TTRHO, DVRHO, RKPRHO, ABRHO, ABVRHO, &
       ARRHO, AR1RHO, AR2RHO,  RJCB, EPSRHO, BPRHO, RMJRHO, RMNRHO, &
       TTRHOG, DVRHOG, RKPRHOG, ABRHOG, ABVRHOG, ARRHOG, AR1RHOG, AR2RHOG, &
       ABB2RHOG, AIB2RHOG, ARHBRHOG, RMJRHOG, RMNRHOG, RDPVRHOG, &
       PSITRHO, PSIPRHO, PPPRHO, PIQRHO, PIRHO, FACTQ, &
       PVOLRHOG, PSURRHOG, ABB1RHO
  REAL(rkind), DIMENSION(:),ALLOCATABLE :: &  ! (NRMP)
       QRHO

!     ****** ADDITIONAL PART BY HONDA MITSURU ******
! TRADD
  REAL(rkind), DIMENSION(3,3)     :: FA, FB, FC
  REAL(rkind), DIMENSION(:)      ,ALLOCATABLE :: & ! (NSTM)
       RTM, AMZ, PEXT, PNSSA, PNSA, PTSA
  REAL(rkind), DIMENSION(:,:)    ,ALLOCATABLE :: & ! (NRM,NSTM)
       PEX, SEX
  REAL(rkind), DIMENSION(:,:,:)  ,ALLOCATABLE :: & ! (NRM,NSM,NSM)
       AKDWD, AKDWP, ADDWD, ADDWP
  REAL(rkind), DIMENSION(:,:,:,:),ALLOCATABLE :: & ! (NVM,NVM,4,3)
       VV,DD
  REAL(rkind), DIMENSION(:,:,:,:),ALLOCATABLE :: & ! (NVM,NVM,2,3)
       VI,DI

!     ****** NCLASS ******
! TRNCL
  REAL(rkind), DIMENSION(:)    ,ALLOCATABLE :: & !  (NRM)
       AJBSNC, ETANC, AJEXNC
  REAL(rkind), DIMENSION(:,:)  ,ALLOCATABLE :: & !  (NRM,NSM)
       CJBSP, CJBST, ADNCG, AVNCG
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: & !  (NRM,NSM,NSM)
       AKNCP, AKNCT, ADNCP, ADNCT, AKLP, AKLD, ADLP, ADLD
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: & !  (NRM,5,NSM)
       RGFLS,   RQFLS
  INTEGER :: MDNCLS, NSLMAX

!     ****** STORED VARIABLES FOR UFILE ******
! TRSVU
  REAL(rkind), DIMENSION(NTUM) :: &
       PNFU, PNFUA, RRU, RAU, PHIAU, VOLAU, RIPU, BBU, RKAPU, PNBIU
  REAL(rkind), DIMENSION(:,:)  ,ALLOCATABLE :: & ! (NTUM,NRMP)
       QPU,  AJU, AJNBU, BPU, PRLU, PECU, POHU, DVRHOU, AJBSU, ZEFFU, PBMU, &
       RNFU, WROTU, ZEFFU_ORG, RKPRHOU, RMJRHOU, RMNRHOU, ARRHOU, AR1RHOU, &
       AR2RHOU, ABRHOU, TTRHOU, SWLU
  REAL(rkind), DIMENSION(:,:)  ,ALLOCATABLE :: & ! (NTUM,NSTM)
       PTSU, PNSU, PTSUA, PNSUA
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: & ! (NTUM,NRMP,NSM)
       RNU, RTU, PNBU, PICU, SNBU, RNU_ORG

!     ************
!TRPROF
  REAL(rkind), DIMENSION(:),ALLOCATABLE :: & ! (NSTM)
       PNSSO,PTSO,PNSSAO,PTSAO

CONTAINS

  SUBROUTINE allocate_trcomm_profile(ierr)
    USE TRCOM0, ONLY: NRMAX, NSTM, NFM, NSM, NEQMAXM, NRMP, NTUM, NTM, NGM, NCGM, NCRTM
    INTEGER, INTENT(OUT) :: ierr
    ierr = 0

    ALLOCATE(RG(NRMAX),RM(NRMAX),RHOM(NRMAX),RHOG(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(BP(NRMAX),RDP(NRMAX),RPSI(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ! Zero-init BP/RDP/RPSI: when libtrapi.so re-ALLOCATEs after a
    ! finalize+init cycle, glibc malloc may return the same chunk that
    ! tst2 freed in DEALLOCATE_TRCOMM, so the new "uninit" memory holds
    ! the previous run's poloidal-field values. trcalc.f90:66 *does*
    ! overwrite BP every step, but RDP feeds into that very assignment
    ! (BP=AR1RHOG*RDP/RR), and stale RDP can leak into BP. Same for
    ! EZOH (1060 below) and any profile that an MDL flag short-circuits
    ! out of being recomputed.
    BP(:)   = 0.D0
    RDP(:)  = 0.D0
    RPSI(:) = 0.D0
    ALLOCATE(RN(NRMAX,NSTM),RT(NRMAX,NSTM),RU(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RW(NRMAX,NFM),RNF(NRMAX,NFM),RTF(NRMAX,NFM),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(ANC(NRMAX),ANFE(NRMAX),ANNU(NRMAX),ZEFF(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PZC(NRMAX),PZFE(NRMAX),BETA(NRMAX),BETAP(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(BETAL(NRMAX),BETAPL(NRMAX),BETAQ(NRMAX),PBM(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PADD(NRMAX),VTOR(NRMAX),VPAR(NRMAX),VPRP(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(VPOL(NRMAX),WROT(NRMAX),ER(NRMAX),VEXB(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(VEXBP(NRMAX),WEXBP(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(WEXB(NRMAX),AGMP(NRMAX),AJ(NRMAX),AJOH(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(EZOH(NRMAX),QP(NRMAX),AJTOR(NRMAX),AJNB(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    EZOH(:)  = 0.D0
    QP(:)    = 0.D0
    AJTOR(:) = 0.D0
    AJNB(:)  = 0.D0
    ALLOCATE(QPINV(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AJRF(NRMAX),AJBS(NRMAX),PNB(NRMAX),SNB(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(SPSC(NRMAX,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PBIN(NRMAX),PNF(NRMAX),SNF(NRMAX),PFIN(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(POH(NRMAX),PRB(NRMAX),PRC(NRMAX),PRSUM(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PRL(NRMAX),PCX(NRMAX),PIE(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(SIE(NRMAX),SCX(NRMAX),TSIE(NRMAX),TSCX(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PIN(NRMAX,NSTM),SSIN(NRMAX,NSTM),PBCL(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(SPE(NRMAX,NSTM),PFCL(NRMAX,NSTM),PRF(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PRFV(NRMAX,NSTM,3),AJRFV(NRMAX,3),RGFLX(NRMAX,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(ETA(NRMAX),S(NRMAX),ALPHA(NRMAX),RKCV(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(TAUB(NRMAX),TAUF(NRMAX),TAUK(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AK(NRMAX,NSTM),AVK(NRMAX,NSTM),AD(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AV(NRMAX,NSTM),AKNC(NRMAX,NSTM),AKDW(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ADNC(NRMAX,NSTM),ADDW(NRMAX,NSTM),AVNC(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AVDW(NRMAX,NSTM),AVKNC(NRMAX,NSTM),AVKDW(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(VGR1(NRMAX,4),VGR2(NRMAX,4),VGR3(NRMAX,4),VGR4(NRMAX,4),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(GRM(NRMAX),GRG(NRMP),GJB(NRMP,4),GAD(NRMP,4),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(GET(NRMP,5),GAK(NRMP,6),GYR(NRMP,8),GER(NRMP,8),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(GVR(NRMP,NGM,NCGM),GVRT(NRMAX,NTM,NCRTM),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(RHOTR(NRMAX),PRHO(NRMAX),HJRHO(NRMAX),VTRHO(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(TRHO(NRMAX),TTRHO(NRMAX),DVRHO(NRMAX),RKPRHO(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ABRHO(NRMAX),ABVRHO(NRMAX),PSITRHO(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PSIPRHO(NRMAX),PPPRHO(NRMAX),PIQRHO(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PIRHO(NRMAX),ARRHO(NRMAX),AR1RHO(NRMAX),AR2RHO(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RJCB(NRMAX),EPSRHO(NRMAX),BPRHO(NRMAX),RMJRHO(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RMNRHO(NRMAX) ,TTRHOG(NRMAX),DVRHOG(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RKPRHOG(NRMAX),ABRHOG(NRMAX),ABVRHOG(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ARRHOG(NRMAX),AR1RHOG(NRMAX),AR2RHOG(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ABB2RHOG(NRMAX),AIB2RHOG(NRMAX),ARHBRHOG(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PVOLRHOG(NRMAX),PSURRHOG(NRMAX),ABB1RHO(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RMJRHOG(NRMAX),RMNRHOG(NRMAX),RDPVRHOG(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(FACTQ(NRMAX),QRHO(NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(RTM(NSTM),AMZ(NSTM),PEXT(NSTM),PNSSA(NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PNSA(NSTM),PTSA(NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ! Zero-init sister arrays of PNSS (PR #119). When NSMAX < NSM
    ! (e.g. tst2 has NSMAX=2 but NSM=4 hard-coded in tr/trcom0.f90:11),
    ! tr_prof_impurity (trprof.f90:319-322,329-331) only writes
    ! PNSSA(1), PNSSA(2:NSMAX), PNSSA(7), PNSSA(8) -- leaving
    ! PNSSA(NSMAX+1 .. NSM) untouched. TR_EDGE_SELECTOR/DETERMINER
    ! (trprof.f90:680-720) then reads PNSSA(NS)/PNSA(NS)/PTSA(NS) for
    ! NS=1..NSM=4 in DO NS=1,NSM loops, getting machine-dependent
    ! garbage that cascades to NaN/negative T in libtrapi.so callers
    ! (libtrapi sees non-zero heap from prior Python+numpy mallocs).
    ! See docs/external-patches/tr/REPORT.md.
    PNSSA(:) = 0.D0
    PNSA(:)  = 0.D0
    PTSA(:)  = 0.D0
    ALLOCATE(PEX(NRMAX,NSTM),SEX(NRMAX,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AKDWD(NRMAX,NSM,NSM),AKDWP(NRMAX,NSM,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ADDWD(NRMAX,NSM,NSM),ADDWP(NRMAX,NSM,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(VV(NEQMAXM,NEQMAXM,4,3),DD(NEQMAXM,NEQMAXM,4,3),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(VI(NEQMAXM,NEQMAXM,2,3),DI(NEQMAXM,NEQMAXM,2,3),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(AJBSNC(NRMAX),ETANC(NRMAX),AJEXNC(NRMAX),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(CJBSP(NRMAX,NSM),CJBST(NRMAX,NSM),ADNCG(NRMAX,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AVNCG(NRMAX,NSM) ,STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AKNCP(NRMAX,NSM,NSM),AKNCT(NRMAX,NSM,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ADNCP(NRMAX,NSM,NSM),ADNCT(NRMAX,NSM,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AKLP(NRMAX,NSM,NSM),AKLD(NRMAX,NSM,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ADLP(NRMAX,NSM,NSM),ADLD(NRMAX,NSM,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RGFLS(NRMAX,5,NSM),RQFLS(NRMAX,5,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(QPU(NTUM,NRMP),AJU(NTUM,NRMP),AJNBU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(BPU(NTUM,NRMP),PRLU(NTUM,NRMP),PECU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(POHU(NTUM,NRMP),DVRHOU(NTUM,NRMP),AJBSU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ZEFFU(NTUM,NRMP),PBMU(NTUM,NRMP),RNFU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(WROTU(NTUM,NRMP),ZEFFU_ORG(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RKPRHOU(NTUM,NRMP),RMJRHOU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RMNRHOU(NTUM,NRMP),ARRHOU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(AR1RHOU(NTUM,NRMP),AR2RHOU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ABRHOU(NTUM,NRMP),TTRHOU(NTUM,NRMP),SWLU(NTUM,NRMP),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PTSU(NTUM,NSTM),PNSU(NTUM,NSTM),PTSUA(NTUM,NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PNSUA(NTUM,NSTM) ,STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(RNU(NTUM,NRMP,NSM),RTU(NTUM,NRMP,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PNBU(NTUM,NRMP,NSM),PICU(NTUM,NRMP,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(SNBU(NTUM,NRMP,NSM),RNU_ORG(NTUM,NRMP,NSM),STAT=ierr)
      IF(ierr /= 0) RETURN

    ALLOCATE(PNSSO(NSTM),PTSO(NSTM),PNSSAO(NSTM),PTSAO(NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ! Zero-init the saved/restored edge profiles. TR_EDGE_SELECTOR
    ! (trprof.f90:680-720) saves PNSS->PNSSO, PTS->PTSO, then later
    ! restores PNSS<-PNSSO, etc., using DO NS=1,NSM (hard-coded NSM=4).
    ! When NSMAX<4 and the process heap is non-zero (libtrapi.so loaded
    ! by Python), PNSSO(3:4)/PNSSAO(3:4) contain junk on the first save
    ! call before the corresponding writer has run, and that junk is
    ! then restored back into PNSS/PNSSA. See REPORT.md.
    PNSSO(:)  = 0.D0
    PTSO(:)   = 0.D0
    PNSSAO(:) = 0.D0
    PTSAO(:)  = 0.D0

    ! Defensive zero-init of every profile array. A standalone tr2 binary
    ! launch starts with a fresh process heap (effectively zero). The
    ! libtrapi.so re-init path (after tr_finalize -> ALLOCATE_TRCOMM
    ! again) goes through glibc malloc, which may return a chunk that
    ! still holds the previous run's values. Without this sweep, fields
    ! like BP/EZOH/RDP retain stale poloidal-field/equilibrium values
    ! from the prior fixture, which then leak into the next test's
    ! tr_set_metric / trcalc step (NaN cascade in tr_iter01-after-
    ! tr_tst2). Zero-init mimics the fresh-process heap that the binary
    ! tr2 has, so consecutive Trlib() instances are reproducible.
    RG(:) = 0.D0; RM(:) = 0.D0; RHOM(:) = 0.D0; RHOG(:) = 0.D0
    RN(:,:) = 0.D0; RT(:,:) = 0.D0; RU(:,:) = 0.D0; RW(:,:) = 0.D0
    RNF(:,:) = 0.D0; RTF(:,:) = 0.D0
    ANC(:) = 0.D0; ANFE(:) = 0.D0; ANNU(:) = 0.D0; ZEFF(:) = 0.D0
    PZC(:) = 0.D0; PZFE(:) = 0.D0
    BETA(:) = 0.D0; BETAP(:) = 0.D0; BETAL(:) = 0.D0; BETAPL(:) = 0.D0
    BETAQ(:) = 0.D0; PBM(:) = 0.D0; PADD(:) = 0.D0
    VTOR(:) = 0.D0; VPAR(:) = 0.D0; VPRP(:) = 0.D0; VPOL(:) = 0.D0
    WROT(:) = 0.D0; ER(:) = 0.D0; VEXB(:) = 0.D0; WEXB(:) = 0.D0
    AGMP(:) = 0.D0; VEXBP(:) = 0.D0; WEXBP(:) = 0.D0
    AJ(:) = 0.D0; AJOH(:) = 0.D0; AJRF(:) = 0.D0; AJBS(:) = 0.D0
    QPINV(:) = 0.D0
    PNB(:) = 0.D0; SNB(:) = 0.D0; PBIN(:) = 0.D0
    PNF(:) = 0.D0; SNF(:) = 0.D0; PFIN(:) = 0.D0; POH(:) = 0.D0
    PRB(:) = 0.D0; PRC(:) = 0.D0; PRL(:) = 0.D0; PRSUM(:) = 0.D0
    PCX(:) = 0.D0; PIE(:) = 0.D0
    SIE(:) = 0.D0; SCX(:) = 0.D0; TSIE(:) = 0.D0; TSCX(:) = 0.D0
    PIN(:,:) = 0.D0; SSIN(:,:) = 0.D0; PBCL(:,:) = 0.D0; SPE(:,:) = 0.D0
    PFCL(:,:) = 0.D0; PRF(:,:) = 0.D0
    PRFV(:,:,:) = 0.D0; AJRFV(:,:) = 0.D0
    RGFLX(:,:) = 0.D0; SPSC(:,:) = 0.D0
    ETA(:) = 0.D0; S(:) = 0.D0; ALPHA(:) = 0.D0; RKCV(:) = 0.D0
    TAUB(:) = 0.D0; TAUF(:) = 0.D0; TAUK(:) = 0.D0
    AK(:,:) = 0.D0; AVK(:,:) = 0.D0; AD(:,:) = 0.D0; AV(:,:) = 0.D0
    AKNC(:,:) = 0.D0; AKDW(:,:) = 0.D0; ADNC(:,:) = 0.D0; ADDW(:,:) = 0.D0
    AVNC(:,:) = 0.D0; AVDW(:,:) = 0.D0; AVKNC(:,:) = 0.D0; AVKDW(:,:) = 0.D0
    VGR1(:,:) = 0.D0; VGR2(:,:) = 0.D0; VGR3(:,:) = 0.D0; VGR4(:,:) = 0.D0
    RHOTR(:) = 0.D0; PRHO(:) = 0.D0; HJRHO(:) = 0.D0; VTRHO(:) = 0.D0
    TRHO(:) = 0.D0; TTRHO(:) = 0.D0; DVRHO(:) = 0.D0; RKPRHO(:) = 0.D0
    ABRHO(:) = 0.D0; ABVRHO(:) = 0.D0
    PSITRHO(:) = 0.D0; PSIPRHO(:) = 0.D0; PPPRHO(:) = 0.D0
    PIQRHO(:) = 0.D0; PIRHO(:) = 0.D0; FACTQ(:) = 0.D0
    ARRHO(:) = 0.D0; AR1RHO(:) = 0.D0; AR2RHO(:) = 0.D0
    RJCB(:) = 0.D0; EPSRHO(:) = 0.D0; BPRHO(:) = 0.D0
    RMJRHO(:) = 0.D0; RMNRHO(:) = 0.D0
    TTRHOG(:) = 0.D0; DVRHOG(:) = 0.D0; RKPRHOG(:) = 0.D0
    ABRHOG(:) = 0.D0; ABVRHOG(:) = 0.D0
    ARRHOG(:) = 0.D0; AR1RHOG(:) = 0.D0; AR2RHOG(:) = 0.D0
    ABB2RHOG(:) = 0.D0; AIB2RHOG(:) = 0.D0; ARHBRHOG(:) = 0.D0
    PVOLRHOG(:) = 0.D0; PSURRHOG(:) = 0.D0; ABB1RHO(:) = 0.D0
    RMJRHOG(:) = 0.D0; RMNRHOG(:) = 0.D0; RDPVRHOG(:) = 0.D0
    QRHO(:) = 0.D0
    RTM(:) = 0.D0; AMZ(:) = 0.D0; PEXT(:) = 0.D0
    PEX(:,:) = 0.D0; SEX(:,:) = 0.D0
    AKDWD(:,:,:) = 0.D0; AKDWP(:,:,:) = 0.D0
    ADDWD(:,:,:) = 0.D0; ADDWP(:,:,:) = 0.D0
    VV(:,:,:,:) = 0.D0; DD(:,:,:,:) = 0.D0
    VI(:,:,:,:) = 0.D0; DI(:,:,:,:) = 0.D0
    AJBSNC(:) = 0.D0; ETANC(:) = 0.D0; AJEXNC(:) = 0.D0
    CJBSP(:,:) = 0.D0; CJBST(:,:) = 0.D0
    ADNCG(:,:) = 0.D0; AVNCG(:,:) = 0.D0
    AKNCP(:,:,:) = 0.D0; AKNCT(:,:,:) = 0.D0
    ADNCP(:,:,:) = 0.D0; ADNCT(:,:,:) = 0.D0
    AKLP(:,:,:) = 0.D0; AKLD(:,:,:) = 0.D0
    ADLP(:,:,:) = 0.D0; ADLD(:,:,:) = 0.D0
    RGFLS(:,:,:) = 0.D0; RQFLS(:,:,:) = 0.D0
    PTSA(:) = 0.D0  ! redundant with line above but kept for clarity

    ! Defensive zero-init (see PR #121/#123 pattern): libtrapi.so
    ! finalize+reinit cycle can reuse heap chunks with stale values.
    ! Extends the PR #121 sweep to: (a) REAL(single) graphics arrays
    ! GRM/GRG/GJB/GAD/GET/GAK/GYR/GER/GVR/GVRT (written one-slice-per-
    ! step by trg*/trgrsl, so earlier time slots carry junk until
    ! filled); and (b) UFILE scratch arrays QPU/AJU/.../SWLU, PTSU/PNSU/
    ! PTSUA/PNSUA, RNU/RTU/PNBU/PICU/SNBU/RNU_ORG — only populated when
    ! MDLUF!=0, leaving every slot stale when MDLUF=0 but still exposed
    ! via trcomm symbols to downstream code / state dumps.
    GRM(:)      = 0.0
    GRG(:)      = 0.0
    GJB(:,:)    = 0.0
    GAD(:,:)    = 0.0
    GET(:,:)    = 0.0
    GAK(:,:)    = 0.0
    GYR(:,:)    = 0.0
    GER(:,:)    = 0.0
    GVR(:,:,:)  = 0.0
    GVRT(:,:,:) = 0.0

    QPU(:,:)       = 0.D0
    AJU(:,:)       = 0.D0
    AJNBU(:,:)     = 0.D0
    BPU(:,:)       = 0.D0
    PRLU(:,:)      = 0.D0
    PECU(:,:)      = 0.D0
    POHU(:,:)      = 0.D0
    DVRHOU(:,:)    = 0.D0
    AJBSU(:,:)     = 0.D0
    ZEFFU(:,:)     = 0.D0
    PBMU(:,:)      = 0.D0
    RNFU(:,:)      = 0.D0
    WROTU(:,:)     = 0.D0
    ZEFFU_ORG(:,:) = 0.D0
    RKPRHOU(:,:)   = 0.D0
    RMJRHOU(:,:)   = 0.D0
    RMNRHOU(:,:)   = 0.D0
    ARRHOU(:,:)    = 0.D0
    AR1RHOU(:,:)   = 0.D0
    AR2RHOU(:,:)   = 0.D0
    ABRHOU(:,:)    = 0.D0
    TTRHOU(:,:)    = 0.D0
    SWLU(:,:)      = 0.D0
    PTSU(:,:)      = 0.D0
    PNSU(:,:)      = 0.D0
    PTSUA(:,:)     = 0.D0
    PNSUA(:,:)     = 0.D0
    RNU(:,:,:)     = 0.D0
    RTU(:,:,:)     = 0.D0
    PNBU(:,:,:)    = 0.D0
    PICU(:,:,:)    = 0.D0
    SNBU(:,:,:)    = 0.D0
    RNU_ORG(:,:,:) = 0.D0
  END SUBROUTINE allocate_trcomm_profile

  SUBROUTINE deallocate_trcomm_profile
    DEALLOCATE(RG,RM,RHOM,RHOG,BP,RDP,RPSI,RN,RT,RU,RW)
    DEALLOCATE(RNF,RTF,ANC,ANFE,ANNU,ZEFF,PZC,PZFE,BETA,BETAP,BETAL,BETAPL)
    DEALLOCATE(BETAQ,PBM,PADD,VTOR,VPAR,VPRP,VPOL,WROT,ER,VEXB,WEXB,AGMP)
    DEALLOCATE(VEXBP,WEXBP)
    DEALLOCATE(AJ,AJOH, EZOH,QP,AJTOR,AJNB,AJRF,AJBS,QPINV)
    DEALLOCATE(PNB,SNB,PBIN,PNF,SNF,PFIN,POH,PRB,PRC,PRL,PRSUM,PCX,PIE)
    DEALLOCATE(SIE,SCX,TSIE,TSCX,PIN,SSIN,PBCL, SPE)
    DEALLOCATE(PFCL,PRF,PRFV,AJRFV,RGFLX)
    DEALLOCATE(ETA,S,ALPHA,RKCV,TAUB,TAUF,TAUK,AK,AVK,AD,AV)
    DEALLOCATE(AKNC,AKDW,ADNC,ADDW,AVNC,AVDW,AVKNC,AVKDW)
    DEALLOCATE(VGR1,VGR2,VGR3,VGR4)
    DEALLOCATE(GRM,GRG,GJB,GAD,GET,GAK,GYR,GER,GVR,GVRT)
    IF(ALLOCATED(GPNB)) DEALLOCATE(GPNB)
    DEALLOCATE(RHOTR,PRHO,HJRHO,VTRHO,TRHO,TTRHO,DVRHO,RKPRHO,ABRHO,ABVRHO)
    DEALLOCATE(PSITRHO,PSIPRHO,PPPRHO,PIQRHO,PIRHO)
    DEALLOCATE(ARRHO,AR1RHO,AR2RHO,RJCB,EPSRHO,BPRHO,RMJRHO,RMNRHO)
    DEALLOCATE(TTRHOG,DVRHOG,RKPRHOG,ABRHOG,ABVRHOG,ARRHOG,AR1RHOG,AR2RHOG)
    DEALLOCATE(ABB2RHOG,AIB2RHOG,ARHBRHOG,RMJRHOG,RMNRHOG,RDPVRHOG,FACTQ,QRHO)
    DEALLOCATE(PVOLRHOG,PSURRHOG,ABB1RHO)
    DEALLOCATE(RTM,AMZ,PEXT,PNSSA,PNSA,PTSA,PEX, SEX,AKDWD)
    DEALLOCATE(AKDWP,ADDWD,ADDWP,VV,DD,VI,DI)
    DEALLOCATE(SPSC)
    DEALLOCATE(AJBSNC, ETANC, AJEXNC,CJBSP,CJBST,ADNCG,AVNCG)
    DEALLOCATE(AKNCP,AKNCT,ADNCP,ADNCT,AKLP,AKLD,ADLP,ADLD,RGFLS,RQFLS)
    DEALLOCATE(QPU,AJU,AJNBU,BPU,PRLU,PECU,POHU,DVRHOU)
    DEALLOCATE(AJBSU,ZEFFU,PBMU,RNFU,WROTU,ZEFFU_ORG,RKPRHOU)
    DEALLOCATE(RMJRHOU,RMNRHOU,ARRHOU,AR1RHOU,AR2RHOU,ABRHOU)
    DEALLOCATE(TTRHOU,SWLU,PTSU,PNSU,PTSUA,PNSUA)
    DEALLOCATE(RNU,RTU,PNBU,PICU,SNBU,RNU_ORG)
    DEALLOCATE(PNSSO,PTSO,PNSSAO,PTSAO)
  END SUBROUTINE deallocate_trcomm_profile

  SUBROUTINE deallocate_err_trcomm_profile
    IF(ALLOCATED(RG       )) DEALLOCATE(RG       )
    IF(ALLOCATED(RM       )) DEALLOCATE(RM       )
    IF(ALLOCATED(RHOM     )) DEALLOCATE(RHOM     )
    IF(ALLOCATED(RHOG     )) DEALLOCATE(RHOG     )
    IF(ALLOCATED(BP       )) DEALLOCATE(BP       )
    IF(ALLOCATED(RDP      )) DEALLOCATE(RDP      )
    IF(ALLOCATED(RPSI     )) DEALLOCATE(RPSI     )
    IF(ALLOCATED(RN       )) DEALLOCATE(RN       )
    IF(ALLOCATED(RT       )) DEALLOCATE(RT       )
    IF(ALLOCATED(RU       )) DEALLOCATE(RU       )
    IF(ALLOCATED(RW       )) DEALLOCATE(RW       )
    IF(ALLOCATED(RNF      )) DEALLOCATE(RNF      )
    IF(ALLOCATED(RTF      )) DEALLOCATE(RTF      )
    IF(ALLOCATED(ANC      )) DEALLOCATE(ANC      )
    IF(ALLOCATED(ANFE     )) DEALLOCATE(ANFE     )
    IF(ALLOCATED(ANNU     )) DEALLOCATE(ANNU     )
    IF(ALLOCATED(ZEFF     )) DEALLOCATE(ZEFF     )
    IF(ALLOCATED(PZC      )) DEALLOCATE(PZC      )
    IF(ALLOCATED(PZFE     )) DEALLOCATE(PZFE     )
    IF(ALLOCATED(BETA     )) DEALLOCATE(BETA     )
    IF(ALLOCATED(BETAP    )) DEALLOCATE(BETAP    )
    IF(ALLOCATED(BETAL    )) DEALLOCATE(BETAL    )
    IF(ALLOCATED(BETAPL   )) DEALLOCATE(BETAPL   )
    IF(ALLOCATED(BETAQ    )) DEALLOCATE(BETAQ    )
    IF(ALLOCATED(PBM      )) DEALLOCATE(PBM      )
    IF(ALLOCATED(PADD     )) DEALLOCATE(PADD     )
    IF(ALLOCATED(VTOR     )) DEALLOCATE(VTOR     )
    IF(ALLOCATED(VPAR     )) DEALLOCATE(VPAR     )
    IF(ALLOCATED(VPRP     )) DEALLOCATE(VPRP     )
    IF(ALLOCATED(VPOL     )) DEALLOCATE(VPOL     )
    IF(ALLOCATED(WROT     )) DEALLOCATE(WROT     )
    IF(ALLOCATED(ER       )) DEALLOCATE(ER       )
    IF(ALLOCATED(VEXB     )) DEALLOCATE(VEXB     )
    IF(ALLOCATED(WEXB     )) DEALLOCATE(WEXB     )
    IF(ALLOCATED(AGMP     )) DEALLOCATE(AGMP     )
    IF(ALLOCATED(VEXBP    )) DEALLOCATE(VEXBP    )
    IF(ALLOCATED(WEXBP    )) DEALLOCATE(WEXBP    )
    IF(ALLOCATED(AJ       )) DEALLOCATE(AJ       )
    IF(ALLOCATED(AJOH     )) DEALLOCATE(AJOH     )
    IF(ALLOCATED(EZOH     )) DEALLOCATE(EZOH     )
    IF(ALLOCATED(QP       )) DEALLOCATE(QP       )
    IF(ALLOCATED(AJTOR    )) DEALLOCATE(AJTOR    )
    IF(ALLOCATED(AJNB     )) DEALLOCATE(AJNB     )
    IF(ALLOCATED(AJRF     )) DEALLOCATE(AJRF     )
    IF(ALLOCATED(AJBS     )) DEALLOCATE(AJBS     )
    IF(ALLOCATED(QPINV    )) DEALLOCATE(QPINV    )
    IF(ALLOCATED(PNB      )) DEALLOCATE(PNB      )
    IF(ALLOCATED(SNB      )) DEALLOCATE(SNB      )
    IF(ALLOCATED(PBIN     )) DEALLOCATE(PBIN     )
    IF(ALLOCATED(PNF      )) DEALLOCATE(PNF      )
    IF(ALLOCATED(SNF      )) DEALLOCATE(SNF      )
    IF(ALLOCATED(PFIN     )) DEALLOCATE(PFIN     )
    IF(ALLOCATED(POH      )) DEALLOCATE(POH      )
    IF(ALLOCATED(PRB      )) DEALLOCATE(PRB      )
    IF(ALLOCATED(PRC      )) DEALLOCATE(PRC      )
    IF(ALLOCATED(PRL      )) DEALLOCATE(PRL      )
    IF(ALLOCATED(PRSUM    )) DEALLOCATE(PRSUM    )
    IF(ALLOCATED(PCX      )) DEALLOCATE(PCX      )
    IF(ALLOCATED(PIE      )) DEALLOCATE(PIE      )
    IF(ALLOCATED(SIE      )) DEALLOCATE(SIE      )
    IF(ALLOCATED(SCX      )) DEALLOCATE(SCX      )
    IF(ALLOCATED(TSIE     )) DEALLOCATE(TSIE     )
    IF(ALLOCATED(TSCX     )) DEALLOCATE(TSCX     )
    IF(ALLOCATED(PIN      )) DEALLOCATE(PIN      )
    IF(ALLOCATED(SSIN     )) DEALLOCATE(SSIN     )
    IF(ALLOCATED(PBCL     )) DEALLOCATE(PBCL     )
    IF(ALLOCATED(SPE      )) DEALLOCATE(SPE      )
    IF(ALLOCATED(PFCL     )) DEALLOCATE(PFCL     )
    IF(ALLOCATED(PRF      )) DEALLOCATE(PRF      )
    IF(ALLOCATED(PRFV     )) DEALLOCATE(PRFV     )
    IF(ALLOCATED(AJRFV    )) DEALLOCATE(AJRFV    )
    IF(ALLOCATED(RGFLX    )) DEALLOCATE(RGFLX    )
    IF(ALLOCATED(SPSC     )) DEALLOCATE(SPSC     )
    IF(ALLOCATED(ETA      )) DEALLOCATE(ETA      )
    IF(ALLOCATED(S        )) DEALLOCATE(S        )
    IF(ALLOCATED(ALPHA    )) DEALLOCATE(ALPHA    )
    IF(ALLOCATED(RKCV     )) DEALLOCATE(RKCV     )
    IF(ALLOCATED(TAUB     )) DEALLOCATE(TAUB     )
    IF(ALLOCATED(TAUF     )) DEALLOCATE(TAUF     )
    IF(ALLOCATED(TAUK     )) DEALLOCATE(TAUK     )
    IF(ALLOCATED(AK       )) DEALLOCATE(AK       )
    IF(ALLOCATED(AVK      )) DEALLOCATE(AVK      )
    IF(ALLOCATED(AD       )) DEALLOCATE(AD       )
    IF(ALLOCATED(AV       )) DEALLOCATE(AV       )
    IF(ALLOCATED(AKNC     )) DEALLOCATE(AKNC     )
    IF(ALLOCATED(AKDW     )) DEALLOCATE(AKDW     )
    IF(ALLOCATED(ADNC     )) DEALLOCATE(ADNC     )
    IF(ALLOCATED(ADDW     )) DEALLOCATE(ADDW     )
    IF(ALLOCATED(AVNC     )) DEALLOCATE(AVNC     )
    IF(ALLOCATED(AVDW     )) DEALLOCATE(AVDW     )
    IF(ALLOCATED(AVKNC    )) DEALLOCATE(AVKNC    )
    IF(ALLOCATED(AVKDW    )) DEALLOCATE(AVKDW    )
    IF(ALLOCATED(VGR1     )) DEALLOCATE(VGR1     )
    IF(ALLOCATED(VGR2     )) DEALLOCATE(VGR2     )
    IF(ALLOCATED(VGR3     )) DEALLOCATE(VGR3     )
    IF(ALLOCATED(VGR4     )) DEALLOCATE(VGR4     )
    IF(ALLOCATED(GRM      )) DEALLOCATE(GRM      )
    IF(ALLOCATED(GRG      )) DEALLOCATE(GRG      )
    IF(ALLOCATED(GJB      )) DEALLOCATE(GJB      )
    IF(ALLOCATED(GAD      )) DEALLOCATE(GAD      )
    IF(ALLOCATED(GET      )) DEALLOCATE(GET      )
    IF(ALLOCATED(GAK      )) DEALLOCATE(GAK      )
    IF(ALLOCATED(GYR      )) DEALLOCATE(GYR      )
    IF(ALLOCATED(GER      )) DEALLOCATE(GER      )
    IF(ALLOCATED(GPNB     )) DEALLOCATE(GPNB     )
    IF(ALLOCATED(GVR      )) DEALLOCATE(GVR      )
    IF(ALLOCATED(GVRT     )) DEALLOCATE(GVRT     )
    IF(ALLOCATED(RHOTR    )) DEALLOCATE(RHOTR    )
    IF(ALLOCATED(PRHO     )) DEALLOCATE(PRHO     )
    IF(ALLOCATED(HJRHO    )) DEALLOCATE(HJRHO    )
    IF(ALLOCATED(VTRHO    )) DEALLOCATE(VTRHO    )
    IF(ALLOCATED(TRHO     )) DEALLOCATE(TRHO     )
    IF(ALLOCATED(TTRHO    )) DEALLOCATE(TTRHO    )
    IF(ALLOCATED(PSITRHO  )) DEALLOCATE(PSITRHO  )
    IF(ALLOCATED(PSIPRHO  )) DEALLOCATE(PSIPRHO  )
    IF(ALLOCATED(PPPRHO   )) DEALLOCATE(PPPRHO   )
    IF(ALLOCATED(PIQRHO   )) DEALLOCATE(PIQRHO   )
    IF(ALLOCATED(PIRHO    )) DEALLOCATE(PIRHO    )
    IF(ALLOCATED(DVRHO    )) DEALLOCATE(DVRHO    )
    IF(ALLOCATED(RKPRHO   )) DEALLOCATE(RKPRHO   )
    IF(ALLOCATED(ABRHO    )) DEALLOCATE(ABRHO    )
    IF(ALLOCATED(ABVRHO   )) DEALLOCATE(ABVRHO   )
    IF(ALLOCATED(ARRHO    )) DEALLOCATE(ARRHO    )
    IF(ALLOCATED(AR1RHO   )) DEALLOCATE(AR1RHO   )
    IF(ALLOCATED(AR2RHO   )) DEALLOCATE(AR2RHO   )
    IF(ALLOCATED(RJCB     )) DEALLOCATE(RJCB     )
    IF(ALLOCATED(EPSRHO   )) DEALLOCATE(EPSRHO   )
    IF(ALLOCATED(BPRHO    )) DEALLOCATE(BPRHO    )
    IF(ALLOCATED(RMJRHO   )) DEALLOCATE(RMJRHO   )
    IF(ALLOCATED(RMNRHO   )) DEALLOCATE(RMNRHO   )
    IF(ALLOCATED(TTRHOG   )) DEALLOCATE(TTRHOG   )
    IF(ALLOCATED(DVRHOG   )) DEALLOCATE(DVRHOG   )
    IF(ALLOCATED(RKPRHOG  )) DEALLOCATE(RKPRHOG  )
    IF(ALLOCATED(ABRHOG   )) DEALLOCATE(ABRHOG   )
    IF(ALLOCATED(ABVRHOG  )) DEALLOCATE(ABVRHOG  )
    IF(ALLOCATED(ARRHOG   )) DEALLOCATE(ARRHOG   )
    IF(ALLOCATED(AR1RHOG  )) DEALLOCATE(AR1RHOG  )
    IF(ALLOCATED(AR2RHOG  )) DEALLOCATE(AR2RHOG  )
    IF(ALLOCATED(ABB2RHOG )) DEALLOCATE(ABB2RHOG )
    IF(ALLOCATED(AIB2RHOG )) DEALLOCATE(AIB2RHOG )
    IF(ALLOCATED(ARHBRHOG )) DEALLOCATE(ARHBRHOG )
    IF(ALLOCATED(RMJRHOG  )) DEALLOCATE(RMJRHOG  )
    IF(ALLOCATED(RMNRHOG  )) DEALLOCATE(RMNRHOG  )
    IF(ALLOCATED(PVOLRHOG )) DEALLOCATE(PVOLRHOG )
    IF(ALLOCATED(PSURRHOG )) DEALLOCATE(PSURRHOG )
    IF(ALLOCATED(ABB1RHO  )) DEALLOCATE(ABB1RHO  )
    IF(ALLOCATED(RDPVRHOG )) DEALLOCATE(RDPVRHOG )
    IF(ALLOCATED(FACTQ    )) DEALLOCATE(FACTQ    )
    IF(ALLOCATED(QRHO     )) DEALLOCATE(QRHO     )
    IF(ALLOCATED(RTM      )) DEALLOCATE(RTM      )
    IF(ALLOCATED(AMZ      )) DEALLOCATE(AMZ      )
    IF(ALLOCATED(PEXT     )) DEALLOCATE(PEXT     )
    IF(ALLOCATED(PNSSA    )) DEALLOCATE(PNSSA    )
    IF(ALLOCATED(PNSA     )) DEALLOCATE(PNSA     )
    IF(ALLOCATED(PTSA     )) DEALLOCATE(PTSA     )
    IF(ALLOCATED(PEX      )) DEALLOCATE(PEX      )
    IF(ALLOCATED(SEX      )) DEALLOCATE(SEX      )
    IF(ALLOCATED(AKDWD    )) DEALLOCATE(AKDWD    )
    IF(ALLOCATED(AKDWP    )) DEALLOCATE(AKDWP    )
    IF(ALLOCATED(ADDWD    )) DEALLOCATE(ADDWD    )
    IF(ALLOCATED(ADDWP    )) DEALLOCATE(ADDWP    )
    IF(ALLOCATED(VV       )) DEALLOCATE(VV       )
    IF(ALLOCATED(DD       )) DEALLOCATE(DD       )
    IF(ALLOCATED(VI       )) DEALLOCATE(VI       )
    IF(ALLOCATED(DI       )) DEALLOCATE(DI       )
    IF(ALLOCATED(AJBSNC   )) DEALLOCATE(AJBSNC   )
    IF(ALLOCATED(ETANC    )) DEALLOCATE(ETANC    )
    IF(ALLOCATED(AJEXNC   )) DEALLOCATE(AJEXNC   )
    IF(ALLOCATED(CJBSP    )) DEALLOCATE(CJBSP    )
    IF(ALLOCATED(CJBST    )) DEALLOCATE(CJBST    )
    IF(ALLOCATED(ADNCG    )) DEALLOCATE(ADNCG    )
    IF(ALLOCATED(AVNCG    )) DEALLOCATE(AVNCG    )
    IF(ALLOCATED(AKNCP    )) DEALLOCATE(AKNCP    )
    IF(ALLOCATED(AKNCT    )) DEALLOCATE(AKNCT    )
    IF(ALLOCATED(ADNCP    )) DEALLOCATE(ADNCP    )
    IF(ALLOCATED(ADNCT    )) DEALLOCATE(ADNCT    )
    IF(ALLOCATED(AKLP     )) DEALLOCATE(AKLP     )
    IF(ALLOCATED(AKLD     )) DEALLOCATE(AKLD     )
    IF(ALLOCATED(ADLP     )) DEALLOCATE(ADLP     )
    IF(ALLOCATED(ADLD     )) DEALLOCATE(ADLD     )
    IF(ALLOCATED(RGFLS    )) DEALLOCATE(RGFLS    )
    IF(ALLOCATED(RQFLS    )) DEALLOCATE(RQFLS    )
    IF(ALLOCATED(QPU      )) DEALLOCATE(QPU      )
    IF(ALLOCATED(AJU      )) DEALLOCATE(AJU      )
    IF(ALLOCATED(AJNBU    )) DEALLOCATE(AJNBU    )
    IF(ALLOCATED(BPU      )) DEALLOCATE(BPU      )
    IF(ALLOCATED(PRLU     )) DEALLOCATE(PRLU     )
    IF(ALLOCATED(PECU     )) DEALLOCATE(PECU     )
    IF(ALLOCATED(POHU     )) DEALLOCATE(POHU     )
    IF(ALLOCATED(DVRHOU   )) DEALLOCATE(DVRHOU   )
    IF(ALLOCATED(AJBSU    )) DEALLOCATE(AJBSU    )
    IF(ALLOCATED(ZEFFU    )) DEALLOCATE(ZEFFU    )
    IF(ALLOCATED(PBMU     )) DEALLOCATE(PBMU     )
    IF(ALLOCATED(RNFU     )) DEALLOCATE(RNFU     )
    IF(ALLOCATED(WROTU    )) DEALLOCATE(WROTU    )
    IF(ALLOCATED(ZEFFU_ORG)) DEALLOCATE(ZEFFU_ORG)
    IF(ALLOCATED(RKPRHOU  )) DEALLOCATE(RKPRHOU  )
    IF(ALLOCATED(RMJRHOU  )) DEALLOCATE(RMJRHOU  )
    IF(ALLOCATED(RMNRHOU  )) DEALLOCATE(RMNRHOU  )
    IF(ALLOCATED(ARRHOU   )) DEALLOCATE(ARRHOU   )
    IF(ALLOCATED(AR1RHOU  )) DEALLOCATE(AR1RHOU  )
    IF(ALLOCATED(AR2RHOU  )) DEALLOCATE(AR2RHOU  )
    IF(ALLOCATED(ABRHOU   )) DEALLOCATE(ABRHOU   )
    IF(ALLOCATED(TTRHOU   )) DEALLOCATE(TTRHOU   )
    IF(ALLOCATED(SWLU     )) DEALLOCATE(SWLU     )
    IF(ALLOCATED(PTSU     )) DEALLOCATE(PTSU     )
    IF(ALLOCATED(PNSU     )) DEALLOCATE(PNSU     )
    IF(ALLOCATED(PTSUA    )) DEALLOCATE(PTSUA    )
    IF(ALLOCATED(PNSUA    )) DEALLOCATE(PNSUA    )
    IF(ALLOCATED(RNU      )) DEALLOCATE(RNU      )
    IF(ALLOCATED(RTU      )) DEALLOCATE(RTU      )
    IF(ALLOCATED(PNBU     )) DEALLOCATE(PNBU     )
    IF(ALLOCATED(PICU     )) DEALLOCATE(PICU     )
    IF(ALLOCATED(SNBU     )) DEALLOCATE(SNBU     )
    IF(ALLOCATED(RNU_ORG  )) DEALLOCATE(RNU_ORG  )
    IF(ALLOCATED(PNSSO    )) DEALLOCATE(PNSSO    )
    IF(ALLOCATED(PTSO     )) DEALLOCATE(PTSO     )
    IF(ALLOCATED(PNSSAO   )) DEALLOCATE(PNSSAO   )
    IF(ALLOCATED(PTSAO    )) DEALLOCATE(PTSAO    )
  END SUBROUTINE deallocate_err_trcomm_profile

END MODULE trcomm_profile
