! wr_graphics_stubs.f90
!
! Phase L-4: minimal stand-ins for the GSAF / graphics entry points that
! libwrapi.so references at load-time even though it excludes all real
! graphics output.
!
! Background: wr itself only calls GUTIME for CPU timing and a couple of
! commented-out PAGES/PAGEE. However the supporting libraries we link in
! (libgrf_pic via plload, libeq_pic via eqgout/eqfile, libpl_pic via
! plprof) contain additional CALL R2W2B / CALL GMNMX1 / CALL PAGES etc.
! references that gfortran -fPIC compiles into GOT indirections. With
! RTLD_LAZY the dynamic loader still resolves GOT entries eagerly for
! GLOB_DAT relocations, so *all* external graphics symbols must be
! present in the .so to let dlopen succeed.
!
! The real GSAF / libgsp / libg3d lives outside libwrapi.so (non-PIC),
! so we provide in-tree empty stubs for every graphics symbol reachable
! through the PIC dependency chain. None of them are exercised by
! wr_init -> wr_run -> wr_finalize so the no-op behaviour is safe; if a
! future caller needs real output the right answer is to add a
! libwrgrf_pic.a rather than to extend these stubs.
!
! Mirrors tr/tr_graphics_stubs.f90 (Phase L-4, PR #35) with additional
! stubs (r2w2b, gmnmx1/2, gqscal, setlin/chs/fnt/rgb, gdefin, gscale,
! ...)  because libwrapi.so links libgrf_pic (tr's libtrapi.so does not,
! because tr doesn't USE plload).

REAL FUNCTION GUCLIP(X)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: X
  GUCLIP = REAL(X)
END FUNCTION GUCLIP

SUBROUTINE PAGES
  IMPLICIT NONE
END SUBROUTINE PAGES

SUBROUTINE PAGEE
  IMPLICIT NONE
END SUBROUTINE PAGEE

SUBROUTINE GUDATE(KK)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(OUT) :: KK
  KK = ' '
END SUBROUTINE GUDATE

SUBROUTINE GUTIME(T)
  ! wr uses GUTIME to sample CPU time (REAL output). Return 0.0 so
  ! the informational "CPU TIME = ..." print stays consistent rather
  ! than emitting an uninitialized value.
  IMPLICIT NONE
  REAL, INTENT(OUT) :: T
  T = 0.0
END SUBROUTINE GUTIME

SUBROUTINE GUFLSH
  IMPLICIT NONE
END SUBROUTINE GUFLSH

! --- libgrf call targets (PAINT_RGB conversion, plotter API) --------

SUBROUTINE R2W2B(FACTOR, RGB)
  IMPLICIT NONE
  REAL, INTENT(IN) :: FACTOR
  REAL, INTENT(OUT) :: RGB(3)
  RGB = 0.0
END SUBROUTINE R2W2B

SUBROUTINE GMNMX1(A, N, M, XMIN, XMAX)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N, M
  REAL, INTENT(IN) :: A(*)
  REAL, INTENT(OUT) :: XMIN, XMAX
  XMIN = 0.0; XMAX = 0.0
END SUBROUTINE GMNMX1

SUBROUTINE GMNMX2(A, NX, NY, NXM, M1, M2, XMIN, XMAX)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NX, NY, NXM, M1, M2
  REAL, INTENT(IN) :: A(*)
  REAL, INTENT(OUT) :: XMIN, XMAX
  XMIN = 0.0; XMAX = 0.0
END SUBROUTINE GMNMX2

SUBROUTINE GQSCAL(XMIN, XMAX, GXMIN, GXMAX, GXSTEP)
  IMPLICIT NONE
  REAL, INTENT(IN) :: XMIN, XMAX
  REAL, INTENT(OUT) :: GXMIN, GXMAX, GXSTEP
  GXMIN = 0.0; GXMAX = 0.0; GXSTEP = 0.0
END SUBROUTINE GQSCAL

SUBROUTINE SETLIN(A, B, C)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: A, B, C
END SUBROUTINE SETLIN

SUBROUTINE SETCHS(A, B)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B
END SUBROUTINE SETCHS

SUBROUTINE SETFNT(A)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: A
END SUBROUTINE SETFNT

SUBROUTINE SETRGB(R, G, B)
  IMPLICIT NONE
  REAL, INTENT(IN) :: R, G, B
END SUBROUTINE SETRGB

SUBROUTINE GDEFIN(A, B, C, D, E, F, G, H)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D, E, F, G, H
END SUBROUTINE GDEFIN

SUBROUTINE GFRAME
  IMPLICIT NONE
END SUBROUTINE GFRAME

SUBROUTINE GSCALE(A, B, C, D, E, F)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D, E
  INTEGER, INTENT(IN) :: F
END SUBROUTINE GSCALE

SUBROUTINE GSCALL(A, B, C, D, E, F)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E, F
END SUBROUTINE GSCALL

SUBROUTINE GVALUE(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GVALUE

SUBROUTINE GVALUL(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GVALUL

SUBROUTINE GPLOTP(X, Y, N, A, B, C, D, E)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N, A, B, C, D, E
  REAL, INTENT(IN) :: X(*), Y(*)
END SUBROUTINE GPLOTP

SUBROUTINE MOVE(A, B)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B
END SUBROUTINE MOVE

SUBROUTINE MOVE2D(A, B)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B
END SUBROUTINE MOVE2D

SUBROUTINE DRAW2D(A, B)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B
END SUBROUTINE DRAW2D

SUBROUTINE OFFCLP(A)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: A
END SUBROUTINE OFFCLP

SUBROUTINE INQLNW(A)
  IMPLICIT NONE
  REAL, INTENT(OUT) :: A
  A = 0.0
END SUBROUTINE INQLNW

SUBROUTINE INQTSZ(A)
  IMPLICIT NONE
  REAL, INTENT(OUT) :: A
  A = 0.0
END SUBROUTINE INQTSZ

INTEGER FUNCTION NGULEN(X)
  IMPLICIT NONE
  REAL, INTENT(IN) :: X
  NGULEN = 1
END FUNCTION NGULEN

! 3D plot symbols (eqg3d/trg3d-style names, only the 3d subset required
! to satisfy libgrf_pic refs; the *.f90 files they live in are NOT in
! libwrapi.so but the call sites inside plgout/plprof inline them).

SUBROUTINE GDEFIN3D(A, B, C, D, E, F, G)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D, E, F, G
END SUBROUTINE GDEFIN3D

SUBROUTINE GAXIS3D(A, B)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B
END SUBROUTINE GAXIS3D

SUBROUTINE GSCALE3DX(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GSCALE3DX

SUBROUTINE GSCALE3DY(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GSCALE3DY

SUBROUTINE GSCALE3DZ(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GSCALE3DZ

SUBROUTINE GVALUE3DX(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GVALUE3DX

SUBROUTINE GVALUE3DY(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GVALUE3DY

SUBROUTINE GVALUE3DZ(A, B, C, D, E)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
  INTEGER, INTENT(IN) :: E
END SUBROUTINE GVALUE3DZ

SUBROUTINE GVIEW3D(A, B, C, D, E, F, G)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D, E, F, G
END SUBROUTINE GVIEW3D

SUBROUTINE CONTF2(A, B, C, D, E, F, G, H)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E
  REAL, INTENT(IN) :: A(*), F(*), G(*)
  INTEGER, INTENT(IN) :: H
END SUBROUTINE CONTF2

SUBROUTINE CONTF3(A, B, C, D, E, F, G, H, I)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I
  REAL, INTENT(IN) :: A(*), F(*), G(*), H
END SUBROUTINE CONTF3

SUBROUTINE CONTF4(A, B, C, D, E, F, G, H, I, J)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I, J
  REAL, INTENT(IN) :: A(*), F(*), G(*), H
END SUBROUTINE CONTF4

SUBROUTINE CONTG2(A, B, C, D, E, F, G, H)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, H
  REAL, INTENT(IN) :: A(*), F(*), G(*)
END SUBROUTINE CONTG2

SUBROUTINE CONTG3(A, B, C, D, E, F, G, H, I)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I
  REAL, INTENT(IN) :: A(*), F(*), G(*), H
END SUBROUTINE CONTG3

SUBROUTINE CONTG4(A, B, C, D, E, F, G, H, I, J)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I, J
  REAL, INTENT(IN) :: A(*), F(*), G(*), H
END SUBROUTINE CONTG4

SUBROUTINE CONTQ2(A, B, C, D, E, F, G, H)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, H
  REAL, INTENT(IN) :: A(*), F(*), G(*)
END SUBROUTINE CONTQ2

SUBROUTINE CONTQ3(A, B, C, D, E, F, G, H, I)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I
  REAL, INTENT(IN) :: A(*), F(*), G(*), H
END SUBROUTINE CONTQ3

SUBROUTINE CONTQ3D1(A, B, C, D, E, F, G, H, I, J)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I, J
  REAL, INTENT(IN) :: A(*), F(*), G(*), H
END SUBROUTINE CONTQ3D1

SUBROUTINE CONTQ4(A, B, C, D, E, F, G, H, I, J)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I, J
  REAL, INTENT(IN) :: A(*), F(*), G(*), H
END SUBROUTINE CONTQ4

SUBROUTINE CPLOT3D1(A, B, C, D, E, F, G, H, I)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I
  REAL, INTENT(IN) :: A(*), F(*), G(*), H(*)
END SUBROUTINE CPLOT3D1

SUBROUTINE GDATA3D1(A, B, C, D, E, F, G, H, I)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: B, C, D, E, I
  REAL, INTENT(IN) :: A(*), F(*), G(*), H(*)
END SUBROUTINE GDATA3D1

SUBROUTINE EQGOUT
  IMPLICIT NONE
END SUBROUTINE EQGOUT

SUBROUTINE W2G2B(FACTOR, RGB)
  IMPLICIT NONE
  REAL, INTENT(IN) :: FACTOR
  REAL, INTENT(OUT) :: RGB(3)
  RGB = 0.0
END SUBROUTINE W2G2B

SUBROUTINE R2Y2W(FACTOR, RGB)
  IMPLICIT NONE
  REAL, INTENT(IN) :: FACTOR
  REAL, INTENT(OUT) :: RGB(3)
  RGB = 0.0
END SUBROUTINE R2Y2W

SUBROUTINE SETCLP(A, B, C, D)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C, D
END SUBROUTINE SETCLP

SUBROUTINE SETLNW(A)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A
END SUBROUTINE SETLNW

SUBROUTINE SETMKS(A, B)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: A
  REAL, INTENT(IN) :: B
END SUBROUTINE SETMKS

SUBROUTINE TEXT(A, N)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: A
  INTEGER, INTENT(IN) :: N
END SUBROUTINE TEXT
