C     $Id: wmcomm.inc,v 1.20 2013/02/06 01:59:45 fukuyama Exp $
C
      USE libmpi 
      USE commpi
      USE libmtx 
      USE plcomm,pt_pl=>PT  ! merge: plcomm_parm gained PT(NSM); wm uses PT as an implicit local scalar
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-F,H,O-Z), INTEGER(I-N)
C     
      include '../dpseki/dpcom1.inc'
      include '../wmseki/wmcom0.inc'
      include '../wmseki/wmcom1.inc'
